---
permalink: san-host/concept_preparing_for_cutover_when_transitioning_san_boot_luns.html
sidebar: sidebar
keywords: ontap, san, host, transition, cutover, phase, san, boot, lun
summary: 'If you are transitioning SAN boot LUNs from Data ONTAP operating in 7-Mode to clustered Data ONTAP, there are certain prerequisites you must be aware of before entering the cutover phase.'
---
= Preparing for the cutover phase when transitioning SAN boot LUNs
:icons: font
:imagesdir: ../media/

[.lead]
If you are transitioning SAN boot LUNs from Data ONTAP operating in 7-Mode to clustered Data ONTAP, there are certain prerequisites you must be aware of before entering the cutover phase.

You must have fabric connectivity and zoning to your clustered Data ONTAP controllers for FC configurations. For iSCSI configurations, your iSCSI sessions must be discovered and logged in to your clustered Data ONTAP controllers. You must also shut down your host.

* For copy-based transitions, you should shut down your host before initiating the Storage Cutover operation in the 7-Mode Transition Tool (7MTT). Copy-free transitions are not supported on HP-UX hosts.
* For copy-free transitions, you should shut down your host before initiating the Export & Halt 7-Mode operation in the 7MTT.
