---
permalink: san-host/task_remounting_dmmp_devices_on_linux_hosts_after_transition.html
sidebar: sidebar
keywords: 
summary: 'After transition from ONTAP operating in 7-Mode to clustered Data ONTAP, you must remount your DMMP devices for RHEL 5 and RHEL 6. Your 7-Mode LUNs are not accessible to the host until your DMMP devices are mounted.'
---
= Remounting DMMP devices on Linux hosts after transition
:icons: font
:imagesdir: ../media/

[.lead]
After transition from ONTAP operating in 7-Mode to clustered Data ONTAP, you must remount your DMMP devices for RHEL 5 and RHEL 6. Your 7-Mode LUNs are not accessible to the host until your DMMP devices are mounted.

If you are doing a copy-free transition (CFT), procedures for vol rehost must be complete. See the _7-Mode Transition Tool Copy-Free Transition Guide_ for details.

* For copy-based transitions, perform these steps after completing the Storage cutover operation in the 7-Mode Transition Tool (7MTT).
* For CFTs perform these steps after the Import Data & Configuration operation in the 7MTT is complete.

. Generate the 7-Mode to ONTAP LUN mapping file:
 ** For copy-based transitions, run the following command from the Linux host where the 7MTT is installed: `transition cbt export lunmap -p project-name -o file_path`
+
For example: `transition cbt export lunmap -p SanWorkLoad -o c:/Libraires/Documents/7-to-C-LUN-MAPPING.csv`

 ** For copy-free transitions, run the following command from the system where the 7MTT is installed: `transition cft export lunmap -p project-name -s svm-name -o output-file`
+
For example: `transition cft export lunmap -p SanWorkLoad -s svml -0 c:/Libraries/Documents/7-to-C-LUN-MAPPING-svml.csv`
+
NOTE: You must run this command for each of your storage virtual machines (SVMs).
. Make a note of the new ONTAP LUN device handle ID from the LUN mapping file.
. Remove the SCSI devices created for 7-Mode LUNs:
 ** To remove all of the SCSI devices: `rescan-scsi-bus.sh -r`
 ** To remove each SCSI device individually: `echo 1> /sys/block/SCSI_ID/delete`
+
This command must be executed on all 7-Mode LUN SCSI devices. See the SCSI Device ID column on the SAN Host LUNs tab of the _Inventory Assessment Workbook_ to identify the SCSI device IDs for the LUNs.
. Discover new ONTAP LUNs: `rescan-scsi-bus.sh`
. Verify that the ONTAP LUNs are discovered: `sanlun lun show`
+
The ONTAP LUN's SCSI devices should be listed under the filename column.

. Configure DMMP devices for ONTAP LUNs: `multipath`
. Verify that the DMMP devices are present: `multipath -ll LUN_SCSI_device_name`
+
In the following example, 3600a098051764937303f4479515a7451 represents the DMMP device handle ID:
+
----
[root@IBMx3550M3-229-169 ~]#multipath -ll /dev/sdq
3600a098051764937303f4479515a7451 dm-6 NETAPP,LUN C-Mode
----

. Mount the LUN: `mount device_namemountpoint`
+
If the mount points are defined in the /etc/fstab file, you can run the mount -a command to mount all of the mount points.

. Verify the mount points: `mount`

*Related information*

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-cft/home.html[Copy-free transition]

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html[Copy-based transition]
