---
permalink: san-host/task_determining_whether_vmfs_volumes_need_to_be_remounted_after_transition.html
sidebar: sidebar
keywords: 
summary: 'After transitioning from Data ONTAP operating in 7-Mode to clustered Data ONTAP, you might have VMFS volumes that need to be remounted to bring VMFS datastores and VMs to their pretransition states.'
---
= Determining whether VMFS volumes need to be remounted after transition
:icons: font
:imagesdir: ../media/

[.lead]
After transitioning from Data ONTAP operating in 7-Mode to clustered Data ONTAP, you might have VMFS volumes that need to be remounted to bring VMFS datastores and VMs to their pretransition states.

* For copy-based transitions, perform these steps before initiating the Storage Cutover operation in the 7-Mode Transition Tool (7MTT).
* For copy-free transitions, perform these steps before initiating the Export & Halt 7-Mode Systems operation in the 7MTT.

. Open the _Inventory Assessment Workbook_ generated by the Inventory Collect Tool (ICT).
. Click the *SAN Host Filesystems* tab.
. Check the *Drive / Mount / Datastore Name* column for the filesystems and datastores mounted on the host before transition.
. Make a note of the corresponding LUN naa IDs in the *SCSI Device ID/Device Name* column for the datastore.
. Check whether the naa IDs noted for the datastore are listed in the 7MTT mapping file that was generated after the transition.
 ** If none of the naa IDs are present in the 7MTT mapping file, the datastore and its underlying LUNs were not part of the 7MTT transition and no remediation is required.
 ** If only part of the naa IDs are present in the 7MTT mapping file, your transition is incomplete and you cannot proceed.
 ** If all naa IDs are present, you must remount your VMFS volumes.

*Related information*

xref:task_remounting_vmfs_volumes_after_transition_using_vsphere_client.adoc[Remounting VMFS volumes after transition using vSphere Client]

xref:task_remounting_vmfs_volumes_after_transition_using_esxi_cli_console.adoc[Remounting VMFS volumes after transition using the ESXi CLI]

xref:concept_what_the_inventory_collect_tool_is.adoc[What the Inventory Collect Tool is]
