---
permalink: san-host/task_preparing_to_transition_solaris_host_data_luns_with_sun_volume_manager.html
sidebar: sidebar
keywords: 
summary: 'Before you transition Solaris host data LUNs with Sun Volume Manager from ONTAP operating in 7-Mode to clustered ONTAP, you must gather information you need for the transition process.'
---
= Preparing to transition Solaris host LUNs with Sun Volume Manager
:icons: font
:imagesdir: ../media/

[.lead]
Before you transition Solaris host data LUNs with Sun Volume Manager from ONTAP operating in 7-Mode to clustered ONTAP, you must gather information you need for the transition process.

This task applies to copy-based transitions and copy-free transitions.

. Display your LUNs to identify the name of the LUNs to be transitioned: `lun show`
+
----
 fas8040-shu01> lun show
        /vol/ufs/ufs1                  5g (5368709120)    (r/w, online, mapped)
        /vol/ufs/ufs2                  5g (5368709120)    (r/w, online, mapped)
        /vol/zfs/zfs1                  6g (6442450944)    (r/w, online, mapped)
        /vol/zfs/zfs2                  6g (6442450944)    (r/w, online, mapped)
----

. On the host, locate the device file name for the LUN: `#sanlun lun show`
+
The device file name is listed in the `device filename` column.
+
----
# sanlun lun show
controller(7mode)/                    device                                            host                  lun
vserver(Cmode)       lun-pathname     filename                                          adapter    protocol   size    mode
--------------------------------------------------------------------------------------------------------------------------
fas8040-shu01        /vol/zfs/zfs2    /dev/rdsk/c0t60A98000383035356C2447384D396550d0s2 scsi_vhci0 FCP        6g      7
fas8040-shu01        /vol/zfs/zfs1    /dev/rdsk/c0t60A98000383035356C2447384D39654Ed0s2 scsi_vhci0 FCP        6g      7
fas8040-shu01        /vol/ufs/ufs2    /dev/rdsk/c0t60A98000383035356C2447384D39654Ad0s2 scsi_vhci0 FCP        5g      7
fas8040-shu01        /vol/ufs/ufs1    /dev/rdsk/c0t60A98000383035356C2447384D396548d0s2 scsi_vhci0 FCP        5g
----

. List and record the SVM, and then get the disks associated with the SVM: `metaset``metaset -s set-name`
+
----
# metaset
Set name = svm, Set number = 1
Host                Owner
  Solarisx2-shu04        Yes
Drive                                            Dbase
/dev/dsk/c0t60A98000383035356C2447384D39654Ad0   Yes
/dev/dsk/c0t60A98000383035356C2447384D396548d0   Yes
----
+
----
# metastat -s svm
svm/d2: Concat/Stripe
    Size: 10452992 blocks (5.0 GB)
    Stripe 0:
        Device                                             Start Block  Dbase   Reloc
        /dev/dsk/c0t60A98000383035356C2447384D396548d0s0          0     No      Yes

svm/d1: Concat/Stripe
    Size: 10452992 blocks (5.0 GB)
    Stripe 0:
        Device                                             Start Block  Dbase   Reloc
        /dev/dsk/c0t60A98000383035356C2447384D39654Ad0s0          0     No      Yes

Device Relocation Information:
Device                                           Reloc  Device ID
/dev/dsk/c0t60A98000383035356C2447384D396548d0   Yes    id1,sd@n60a98000383035356c2447384d396548
/dev/dsk/c0t60A98000383035356C2447384D39654Ad0   Yes    id1,sd@n60a98000383035356c2447384d39654a
----

. List and record the mount points: `df –ah`
+
----
# df -ah
Filesystem             size   used  avail capacity  Mounted on
/dev/md/svm/dsk/d1     4.9G   1.5G   3.4G    31%    /d1
/dev/md/svm/dsk/d2     4.9G   991M   3.9G    20%    /d2
----
