---
permalink: san-host/task_testing_dmmp_devices_on_rhel_before_cutover.html
sidebar: sidebar
keywords: ontap, san, host, transition, dmmp, file, systems, rhel, cutover, copy, based
summary: 'If you are using the 7-Mode Transition Tool \(7MTT\) 2.2 or later and Data ONTAP 8.3.2 or later to transition your Red Hat Enterprise Linux \(RHEL\) 5 host, you can test your transitioned clustered Data ONTAP LUNs to verify that you can bring your host and applications online before the cutover phase. Your source host can continue to run I/O to your source 7-Mode LUNs during testing.'
---
= Testing DMMP devices without file systems on RHEL hosts before the cutover phase of copy-based transitions
:icons: font
:imagesdir: ../media/

[.lead]
If you are using the 7-Mode Transition Tool (7MTT) 2.2 or later and Data ONTAP 8.3.2 or later to transition your Red Hat Enterprise Linux (RHEL) 5 host, you can test your transitioned clustered Data ONTAP LUNs to verify that you can bring your host and applications online before the cutover phase. Your source host can continue to run I/O to your source 7-Mode LUNs during testing.

Your new clustered Data ONTAP LUNs must be mapped to your test host and your LUNs must be ready for transition.

You should maintain hardware parity between the test host and the source host and you should perform the following steps on the test host.

Your clustered Data ONTAP LUNs are in read/write mode during testing. They convert to read-only mode when testing is complete and you are preparing for the cutover phase.

.Steps
. After the baseline data copy is complete, select *Test Mode* in the 7MTT user interface (UI).
. In the 7MTT UI, click *Apply Configuration*.
. Rescan your new clustered Data ONTAP LUNs on the test host:
+
`*rescan-scsi-bus.sh*`
. Obtain the new SCSI device names for the clustered Data ONTAP LUNs:
+
`*sanlun lun show*`
+
In the following example, `/dev/sdl` is the SCSI device name for the `lun_dmmp_raw` LUN, and `/dev/sdk` is the SCSI device name for the `lun_dmmp_raw_alias` LUN:
+
----
[root@ibmx3550-229-108 /]# sanlun lun show
controller(7mode/E-Series)/
vserver (cDOT/FlashRay lun-pathname   filename
------------------------------------------------------------------------
vs_brb   /vol/dmmp_raw_vol/lun_dmmp_raw             /dev/sdl
vs_brb   /vol/dmmp_raw_alias_vol/lun_dmmp_raw_alias	/dev/sdk
----

. Obtain the device handle IDs (WWIDs) for the clustered Data ONTAP LUNs:
+
`*/sbin/scsi_id -g-u-s /block/__SCSI_device_name__*`
+
The following is an example of a WWID: "`3600a09804d532d79565d47617679764d`"

. Check whether an alias is defined in the `/etc/multipath.conf` file on the source host.
. If there is an alias defined on the source host, add the alias to the `/etc/multipath.conf` file on the test host, but replace the 7-Mode device handle ID with the clustered Data ONTAP LUN ID.
. Update the DMMP alias settings:
+
`*multipath*`
. Verify that the DMMP alias name correctly references the clustered Data ONTAP LUN:
+
`*multipath -ll*`
. Perform your testing as needed.
. After you have completed your testing, shut down the test host:
+
`*shutdown -h -t0 now*`
. In the 7MTT UI, click *Finish Testing*.

If your clustered Data ONTAP LUNs are to be remapped to your source host, you must prepare your source host for the cutover phase. If your clustered Data ONTAP LUNs are to remain mapped to your test host, no further steps are required on the test host.

*Related information*

xref:task_gathering_pretransition_information_from_inventory_assessment_workbook.adoc[Gathering pretransition information from the Inventory Assessment Workbook]

xref:task_verifying_that_rhel_luns_are_ready_for_transition_using_inventory_assessment_workbook.adoc[Verifying that RHEL LUNs are ready for transition using the Inventory Assessment Workbook]

xref:task_preparing_for_cutover_when_transitioning_linux_host_dmmp_device_without_file_system.adoc[Preparing for cutover when transitioning a Linux host DMMP device without a file system]
