---
permalink: san-host/task_mounting_hp_ux_host_luns_with_file_systems_after_transition.html
sidebar: sidebar
keywords: ontap, san, host, transition, mount, hp, ux, host, lun, file, system
summary: 'After transitioning HP-UX host LUNs with file systems from Data ONTAP operating in 7-Mode to clustered Data ONTAP, you must mount the LUNs.'
---
= Mounting HP-UX host LUNs with file systems after transition
:icons: font
:imagesdir: ../media/

[.lead]
After transitioning HP-UX host LUNs with file systems from Data ONTAP operating in 7-Mode to clustered Data ONTAP, you must mount the LUNs.

For copy-based transitions, perform these steps after completing the Storage Cutover operation in the 7-Mode Transition Tool (7MTT). Copy-free transitions are not supported for HP-UX hosts.

.Steps
. Discover new clustered Data ONTAP LUNs:
+
`*ioscan -fnC disk*`
. Verify that the clustered Data ONTAP LUNs have been discovered:
+
`*sanlun lun show*`
. Verify that the `lun-pathname` for the clustered Data ONTAP LUNs is the same as the `lun-pathname` for the 7-Mode LUNs prior to transition.
. Verify that the output in the mode column has changed from `7` to `C`.
. Use the `mapfile` file to import the volume group:
+
`*vgimport -s -v -m /tmp/mapfile.vg01 /dev/vg01"*`
. Activate the logical volumes:
+
`*vgchange -a y _vg_name_*`
. Convert the legacy Device Special Filename (DSF) to persistent DSF:
+
`*vgdsf -c /dev/vg01*`
. Verify that the VG Status is displayed as available:
+
`*vgdisplay*`
. Manually mount each of the devices:
+
`*mount -F vxfs -o largefiles _device_name mount_point_*`
. Run the fsck command if you are prompted to do so.
. Verify the mount points:
+
`*bdf*`
+
The following example shows how the mount points should be displayed:
+
----
bash-2.05# bdf
Filesystem          kbytes     used     avail     used   Mounted on
/dev/vg01/lvol1   23592960   1050952   22189796    5%   /mnt/qa/vg01
/dev/vg01/lvol2   23592960    588480   22645044    3%   /mnt/qa/vg02
----

*Related information*

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html[Copy-based transition]
