---
permalink: san-host/task_preparing_for_cutover_when_transitioning_solaris_host_sun_volume_manager_data_luns.html
sidebar: sidebar
keywords: 
summary: 'If you are transitioning a Solaris host data LUN with Sun Volume Manager from Data ONTAP operating in 7-Mode to clustered Data ONTAP, you must perform certain steps before entering the cutover phase.'
---
= Preparing for cutover phase when transitioning Solaris host Sun Volume Manager data LUNs
:icons: font
:imagesdir: ../media/

[.lead]
If you are transitioning a Solaris host data LUN with Sun Volume Manager from Data ONTAP operating in 7-Mode to clustered Data ONTAP, you must perform certain steps before entering the cutover phase.

If you are using an FC configuration, fabric connectivity and zoning to the clustered Data ONTAP nodes must be established.

If you are using an iSCSI configuration, the iSCSI sessions to the clustered Data ONTAP nodes must be discovered and logged in.

For copy-based transitions, perform these steps before initiating the Storage Cutover operation in the 7-Mode Transition Tool (7MTT).

For copy-free transitions, perform these steps before initiating the Export & Halt 7-Mode operation in 7MTT.

. Stop I/O on all mount points.
. Shut down each application accessing the LUNs according to the recommendations of the application vendor.
. Unmount all of the mount points: `umount mount_point`
+
----
#umount /d1
#umount /d2
----

. Perform the following operations on metaset: `metaset –s set-name –A disable``metaset –s set-name –r``metaset –s set-name –P`
+
----
metaset -s n_vg -A disable
metaset -s n_vg -r
metaset -s n_vg -P
----
