---
permalink: san-host/task_testing_transitioned_luns_on_windows_hosts_before_cutover.html
sidebar: sidebar
keywords: 
summary: 'If you are using the 7-Mode Transition Tool \(7MTT\) 2.2 or later and Data ONTAP 8.3.2 or later to transition your Windows host LUNs, you can test your transitioned clustered Data ONTAP LUNs to verify that you can bring your disk online and that your application operations work as expected before the cutover phase. Your source host can continue to run I/O to your source 7-Mode LUNs during testing.'
---
= Testing transitioned LUNs on Windows hosts before the cutover phase
:icons: font
:imagesdir: ../media/

[.lead]
If you are using the 7-Mode Transition Tool (7MTT) 2.2 or later and Data ONTAP 8.3.2 or later to transition your Windows host LUNs, you can test your transitioned clustered Data ONTAP LUNs to verify that you can bring your disk online and that your application operations work as expected before the cutover phase. Your source host can continue to run I/O to your source 7-Mode LUNs during testing.

Your 7-Mode LUNs must be ready for transition.

You should maintain hardware parity between the test host and the source host, and you should perform the following steps on the test host.

Your clustered Data ONTAP LUNs are in read/write mode during testing. They convert to read-only mode when testing is complete and you are preparing for the cutover phase.

. After the baseline data copy is complete, select *Test Mode* in the 7MTT user interface (UI).
. In the 7MTT UI, click *Apply configuration*.
. Generate the 7-Mode to clustered Data ONTAP LUN mapping file:
 ** For copy-based transitions, run the following command from the host where the 7MTT is installed: `transition cbt export lunmap -p project-name -o file_path`
+
For example: `transition cbt export lunmap -p SanWorkLoad -o c:/Libraires/Documents/7-to-C-LUN-MAPPING.csv`

 ** For copy-free transitions, run the following command from the system where the 7MTT is installed: `transition cft export lunmap -p project-name -s svm-name -o output-file`
+
NOTE: You must run this command for each of your storage virtual machines (SVMs).
+
For example: `transition cft export lunmap -p SANWorkLoad -s svml -o c:/Libraries/Documents/7-to-C-LUN-MAPPING-svml.csv`
. Bring the transitioned disks and applications online:
 ** If the transitioned disks are not part of Cluster Failover, use the Windows Disk Manager to bring the disks online.
 ** If the transitioned disks are part of Cluster Failover, use the Cluster Failover Manager to bring the disks online.
. Perform your testing as needed.
. After your testing is complete, take your applications and disks offline:
 ** If the transitioned disks are not part of Cluster Failover, use the Windows Disk Manager to take the disks offline.
 ** If the transitioned disks are part of Cluster Failover, use the Cluster Failover Manager to take the disks offline.

If your clustered Data ONTAP LUNs are to be remapped to your source host, you must prepare your source host for the cutover phase. If your clustered Data ONTAP LUNs are to remain mapped to your test host, no further steps are required on the test host.
