---
permalink: san-host/task_reregistering_vms_after_transition_on_non_san_boot_esxi_host_using_vsphere_client.html
sidebar: sidebar
keywords: 
summary: 'After you transition a non-SAN booted host, you must reregister your Virtual Machines \(VMs\).'
---
= Reregistering VMs after transition on non-SAN boot ESXi hosts using vSphere Client
:icons: font
:imagesdir: ../media/

[.lead]
After you transition a non-SAN booted host, you must reregister your Virtual Machines (VMs).

The host must be online and the LUNs must be discovered.

* For copy-based transitions, perform these steps before initiating the Storage Cutover operation in the 7-Mode Transition Tool.
* For copy-free transitions, perform these steps before initiating the Export & Halt 7-Mode Systems operation in the 7MTT.

. Open the _Inventory Assessment Workbook_ generated by the Inventory Collect Tool (ICT).
. Navigate to the Host VMs tab, and then record the *VM Config File* path and *Location/Datastore Name* of the VM.
. Use vSphere Client to log in to the ESXi host or the vCenter Server managing the ESXi host.
. Under *Host and Clusters*, select the ESXi host.
. Navigate to *Configuration* > *Hardware* > *Storage*.
. Select the datastore with the datastore name you previously noted.
. Right click and select *Browse Datastore*.
+
The Datastore Browser window opens.

. Navigate to the *VM Config File* path you previously noted.
. Right click the .vmx file, and then select *Add To Inventory*.
. Repeat these steps for each VM listed in the *Host VMs* tab in the _Inventory Assessment Workbook_ generated by the ICT.
