---
permalink: san-host/task_preparing_for_cutover_when_transitioning_linux_host_file_systems_on_lvm_devices.html
sidebar: sidebar
keywords: ontap, san, host, transition, cutover, phase, host, lvm, device
summary: 'If you are transitioning a Linux host file system on a Logical Volume Manager \(LVM\) device, there are steps you must perform before the cutover phase.'
---
= Preparing for cutover phase when transitioning Linux host file systems on LVM devices
:icons: font
:imagesdir: ../media/

[.lead]
If you are transitioning a Linux host file system on a Logical Volume Manager (LVM) device, there are steps you must perform before the cutover phase.

* For FC configurations, you must have fabric connectivity and zoning to clustered Data ONTAP controllers.
* For iSCSI configurations, your iSCSI sessions must be discovered and logged in to your clustered Data ONTAP controllers.
* You must have the following pretransition information gathered from the _Inventory Assessment Workbook_:
 ** The DMMP device names used by the LVM
 ** The volume group name
 ** The logical volume name
 ** The file system configured on the logical volume device
 ** The directory on which the logical volumes are mounted
* For copy-based transitions, perform these steps before initiating the Storage Cutover operation in the 7-Mode Transition Tool (7MTT).
* For copy-free transitions, perform these steps before initiating the Export & Halt 7-Mode operation in the 7MTT.

.Steps
. Stop I/O to LV mount points.
. Shut down the applications accessing the LUNs according to application vendor's recommendations.
. Unmount the LV mount point:
+
`*umount _dir_name_*`
. Disable the logical volume:
+
`*vgchange -an _vg_name_*`
. Verify the logical volume status:
+
`*lvdisplay _dir_name_*`
+
The LV status should display "`NOT available`".

. Export the volume group:
+
`*vgexport _vg_name_*`
. Verify the VG status:
+
`*vgdisplay _vg_name_*`
+
The VG status should display "`exported`".

. Flush the 7-Mode DDMP device IDs:
+
`*multipath -f _device_name_*`

*Related information*

xref:task_gathering_pretransition_information_from_inventory_assessment_workbook.adoc[Gathering pretransition information from the Inventory Assessment Workbook]
