---
permalink: san-host/task_gathering_pretransition_information_from_inventory_assessment_workbook.html
sidebar: sidebar
keywords: ontap, san, host, transition, pretransition, information, inventory, assessment, workbook
summary: 'There is information in the Inventory Assessment Workbook that you need in various phases of the transition. You should gather and record this information before you begin the transition so that you can reference it as needed throughout the process.'
---
= Gathering pretransition information from the Inventory Assessment Workbook
:icons: font
:imagesdir: ../media/

[.lead]
There is information in the _Inventory Assessment Workbook_ that you need in various phases of the transition. You should gather and record this information before you begin the transition so that you can reference it as needed throughout the process.

.Steps
. Use the Inventory Collect Tool (ICT) to generate the _Inventory Assessment Workbook_.
. Open the _Inventory Assessment Workbook_.
. Go to the *LUN* tab.
. In the *LUN name* column, identify and record the name of the LUN to be transitioned.
. Go to the *SAN Host LUNs* tab.
. In the *SCSI Device ID* column, identify and record the SCSI device name.
. In the *OS Device ID* column, identify and record the DMMP device name for the LUN to be transitioned.
. In the *Filesystems* column, identify and record the file system configured on the DMMP device.
. In the *UUID* column, identify and record the UUID number for the LUN.
. In the *Mount* column, identify and record the directory on which the DMMP device is mounted.
. Go to the *LVMs* tab.
. In the *Physical Volume Name* column, identify and record the DMMP devices that are used by the logical volume.
. Go to the *SAN Host LVMs* tab.
. In the *Volume Group Name* column, identify and record the volume group.
. In the *Logical Volume Path* column, identify and record the logical volume.
. Go to the *SAN Host Filesystems* tab.
. In the *Filesystem* column, identify and record the file system configured on the logical volume.
. In the *Mount* column, identify and record the directory to which the logical volumes are mounted.
. Go to the *GRUB Configuration* tab.
. In the *initrd* column, identify and record the initrd image to be modified.
. Go to the *SAN Host HBAs* tab.
+
You can also see the *iSCSI SAN Interfaces* tab to identify the iSCSI IQN number and IP addresses that are configured on 7-Mode controllers.

. In the *Target IPs (iSCSI)* column identify and record the iSCSI sessions for the 7-Mode controllers.

*Related information*

xref:concept_what_the_inventory_collect_tool_is.adoc[What the Inventory Collect Tool is]
