---
permalink: san-host/task_enabling_caw_on_a_datastore_using_esxi_cli.html
sidebar: sidebar
keywords: 
summary: 'If you did not have support for Compare and Write \(CAW\) in Data ONTAP operating in 7-Mode, you must manually enable CAW support when you transition to clustered Data ONTAP. Clustered Data ONTAP supports CAW by default.'
---
= Enabling CAW on a datastore using the ESXi CLI
:icons: font
:imagesdir: ../media/

[.lead]
If you did not have support for Compare and Write (CAW) in Data ONTAP operating in 7-Mode, you must manually enable CAW support when you transition to clustered Data ONTAP. Clustered Data ONTAP supports CAW by default.

* There must be no I/O or VMs actively running on the VMFS datastore.
* The datastore must be remounted, if it was migrated.
* You must have the new ONTAP LUN naa ID from the 7-Mode Transition Tool (7MTT) mapping file.

CAW must be enabled only when no I/O or VMs are actively running on the VMFS datastore.

* CAW must be enabled only when no I/O or VMs are actively running on the VMFS datastore.
* For copy-based transitions, perform these steps after completing the Storage cutover operation in the 7MTT.
* For copy-free transitions, perform these steps after the Import Data & Configuration operation in the 7MTT is complete.

. Open the _Inventory Assessment Workbook_ generated by the Inventory Collect Tool (ICT).
. Navigate to the SAN Host Filesystems tab.
. Verify the CAW status for the datastore.
+
The *ATS/CAW* value for the datastore should display *Disabled*, and the Filesystem column should display *VMFS.x*.

. Note the name of the datastore in the Disk column
. Log in to the ESXi console using SSH.
. List the device and partition details: `~ # vmkfstools -Ph -v1 datastore_path`
+
datastore_path is the datastore name from the Disk column of the _Inventory Assessment Workbook_.
+
`# vmkfstools -Ph -v1 /vmfs/volumes/datastorename`
+
----
VMFS-5.60 file system spanning 1 partitions.
File system label (if any): datastorename
Mode: public
Capacity 9.8 GB, 8.2 GB available, file block size 1 MB, max file size 64
TB
Volume Creation Time: Mon Dec 9 10:29:18 2013
Files (max/free): 27408/27394
Ptr Blocks (max/free): 64512/64495
Sub Blocks (max/free): 3968/3964
Secondary Ptr Blocks (max/free): 256/256
File Blocks (overcommit/used/overcommit %): 0/1593/0
Ptr Blocks (overcommit/used/overcommit %): 0/17/0
Sub Blocks (overcommit/used/overcommit %): 0/4/0
Volume Metadata size: 590675968
UUID: 52a59b7e-52d2fb6c-11d6-001ec9d631cb
Partitions spanned (on "lvm"):
naa.600a098044314c6c442b446d51376749:1
naa.600a098054314c6c445d446f79716431:1
naa.600a098054314c6c445d446f79716433:1
Is Native Snapshot Capable: YES
----

. Note the first device name and partition number.
+
In the preceding example, naa.600a098044314c6c442b446d51376749:1 is the device name and partition number.

. Use the device ID and partition number to enable CAW on the datastore: `~# vmkfstools --configATSOnly 1 /vmfs/devices/disks/device-ID:Partition`
. Verify that the VMFS volume has been configured with ATS only: `# vmkfstools -Ph -v1 /vmfs/volumes/VMFS-volume-name`
+
----
VMFS-5.54 file system spanning 1 partitions.
File system label (if any): ats-test-1
Mode: public ATS-only
----

*Related information*

xref:task_remounting_vmfs_volumes_after_transition_using_vsphere_client.adoc[Remounting VMFS volumes after transition using vSphere Client]

xref:task_remounting_vmfs_volumes_after_transition_using_esxi_cli_console.adoc[Remounting VMFS volumes after transition using the ESXi CLI]

https://pubs.vmware.com/vsphere-55/index.jsp?topic=/com.vmware.vsphere.storage.doc/GUID-6887003D-2322-49AC-A56C-7AFE7350DB5D.html[VMware documentation]
