---
permalink: san-host/task_preparing_for_post_transition_esxi_host_remediation.html
sidebar: sidebar
keywords: ontap, san, host, transition, post, esxi, host, remediation
summary: 'After the 7-Mode Transition Tool \(7MTT\) transition is complete, you must perform various ESXi host remediation tasks. There are several steps you must complete before you can perform those tasks.'
---
= Preparing for post-transition ESXi host remediation
:icons: font
:imagesdir: ../media/

//
//Fix copy=free link
//

[.lead]
After the 7-Mode Transition Tool (7MTT) transition is complete, you must perform various ESXi host remediation tasks. There are several steps you must complete before you can perform those tasks.

* For copy-based transitions (CBTs), perform these steps before initiating the Storage Cutover operation in the 7MTT.
* For copy-free transitions (CFTs), perform these steps before initiating the Export & Halt 7-Mode Systems operation in the 7MTT.

.Steps
. Generate the 7-Mode to ONTAP LUN mapping file:
 ** For CBTs, run the following command from the Linux host where 7MTT is installed:
 +
`*transition cbt export lunmap -p _project-name_ -o _file_path_*`
+
For example:
+
`*transition cbt export lunmap -p SanWorkLoad -o c:/Libraires/Documents/7-to-C-LUN-MAPPING.csv*`

 ** For CFTs, run the following command from the system where the 7MTT is installed:
 +
`*transition cft export lunmap -p _project-name_ -s _svm-name_ -o _output-file_*`
+
For example:
+
`*transition cft export lunmap -p SanWorkLoad -s svm1 -o c:/Libraires/Documents/7-to-C-LUN-MAPPING-svm1.csv*`
+
NOTE: You must run this command for each of your storage virtual machines (SVMs).

. Verify that igroup and initiator mappings are present.
+
7MTT re-creates the same igroup with initiators used in Data ONTAP operating in 7-Mode, and remaps the clustered Data ONTAP LUN to the host.

. Verify that zoning is appropriate for the new clustered Data ONTAP target.
. If you are doing a copy-free transition (CFT), run `vol rehost`.
+
See the link:https://docs.netapp.com/us-en/ontap-7mode-transition/copy-free/index.html[7-Mode Transition Tool Copy-Free Transition Guide] for `vol rehost` procedures.
