---
permalink: san-host/task_replacing_7_mode_wwids_on_linux_host_after_transition_of_luns.html
sidebar: sidebar
keywords: ontap, san, host, transition, 7, mode, wwids, linux, lun
summary: 'After LUN transition, the 7-Mode LUN WWID changes. You must replace it with the corresponding ONTAP LUN WWID before you can begin servicing data.'
---
= Replacing 7-Mode LUN WWIDs on Linux hosts after transition of LUNs
:icons: font
:imagesdir: ../media/

[.lead]
After LUN transition, the 7-Mode LUN WWID changes. You must replace it with the corresponding ONTAP LUN WWID before you can begin servicing data.

If you are doing a copy-free transition (CFT), then procedures for vol rehost must be complete.

See the link:https://docs.netapp.com/us-en/ontap-7mode-transition/copy-free/index.html[7-Mode Transition Tool Copy-Free Transition Guide]for details.

* For copy-based transitions (CBTs), perform these steps after completing the Storage cutover operation in the 7MTT.
* For CFTs, perform these steps after the Import Data & Configuration operation in the 7MTT is complete.

.Steps
. Generate the 7-Mode to ONTAP LUN mapping file:
 ** For CBTs, run the following command from the Linux host where the 7MTT is installed:
 +
`*transition cbt export lunmap -p project-name -o _file_path_*`
+
For example:
+
`*transition cbt export lunmap -p SanWorkLoad -o c:/Libraires/Documents/7-to-C-LUN-MAPPING.csv*`

 ** For CFTs, run the following command from the system where the 7MTT is installed:
 +
`*transition cft export lunmap -p _project-name_ -s _svm-name_ -o _output-file_*`
+
For example:
+
`*transition cft export lunmap -p SanWorkLoad -s svml -0 c:/Libraries/Documents/7-to-C-LUN-MAPPING-svml.csv*`
+
NOTE: You must run this command for each of your storage virtual machines (SVMs).

. Make a note of the new ONTAP LUN device handle ID from the LUN mapping file.
. Remove the SCSI devices created for 7-Mode LUNs:
 ** To remove all of the SCSI devices:
 +
`*rescan-scsi-bus.sh -r*`
 ** To remove each SCSI device individually:
 +
`*echo 1> /sys/block/__SCSI_ID__/delete*`
+
This command must be executed on all 7-Mode LUN SCSI devices. See the SCSI Device ID column on the SAN Host LUNs tab of the _Inventory Assessment Workbook_ to identify the SCSI device IDs for the LUNs.
. Discover new ONTAP LUNs:
+
`*rescan-scsi-bus.sh*`
. Identify the SCSI devices of the new ONTAP LUNs:
+
`*sanlun lun show*`
. Get the WWIDs for the new ONTAP LUNs:
+
`*/lib/udev/scsi_id -g -u -d /dev _SCSI_dev_*`
. If a DMMP alias is defined, then update the /etc/multipath.conf file to replace the 7-Mode LUN WWID with its corresponding ONTAP LUN WWID, so that the DMMP alias points to the clustered Data ONTAP LUN:
+
`*cat /etc/multipath.conf*`
. Configure the DMMP devices:
+
`*multipath*`
. Verify that the DMMP alias is correctly referencing the ONTAP LUN WWID:
+
`*multipath -11*`
+
In the following sample output, the DMMP alias `dmmp_raw_lun` is referencing `3600a098051764b2d4f3f453135452d31` as the ONTAP WWID:
+
----
root@IBMx3550M3-229-169 ~]# multipath -ll dmmp_raw_lun
dmmp_raw_lun (3600a098051764b2d4f3f453135452d31) dm-8 NETAPP, LUN C-Mode
[size=1.0G] [features=3 queue_if_no_path pg_init_retries 50] [hwhandler=1 alua] [rw]
\_round-robin 0 [prio=50][enabled]
 \_5:0:0:6 sdx 	65:112 [active][ready]
	\_8:0:0:6 sdab 65:176 [active][ready]
\_round-robin 0 [prio=10][enabled]
 \_6:0:0:6 sdy 	65:128 [active][ready]
	\_7:0:0:6 sdaa 65:160 [active][ready]
----
