---
permalink: san-host/task_preparing_rhel_luns_transition_using_inventory_assessment_workbook.html
sidebar: sidebar
keywords: rhel, lun, mount, points, dmmp, device, names, inventory, assessment, workbook
summary: 'Before transition of a LUN with a mount point using a DMMP device name, you must replace the DMMP device name with its respective file system UUID number. This applies to Red Hat Enterprise Linux \(RHEL\) 5 and RHEL 6.'
---
= Preparing RHEL LUNs with mount points using DMMP device names for transition using the Inventory Assessment Workbook
:icons: font
:imagesdir: ../media/

[.lead]
Before transition of a LUN with a mount point using a DMMP device name, you must replace the DMMP device name with its respective file system UUID number. This applies to Red Hat Enterprise Linux (RHEL) 5 and RHEL 6.

This procedure applies to copy-based transitions and copy-free transitions.

.Steps
. Gather pretransition information from the _Inventory Assessment Workbook_.
+
Specifically, you need the following information:

 ** The file system configured on the DMMP device
 ** The directory on which the DMMP device is mounted
 ** The file system UUID for the DMMP device

.Steps
. Verify that the mount points for the DMMP device are defined in the `/etc/fstab `file.
. Create a backup of the file:
+
`*cp /etc/fstab /etc/fstab_pre_transition*`
. Edit the `/etc/fstab` file to replace the DMMP device name with its respective file system UUID number.
+
In the following example, the DMMP device /dev/mapper/360a9800037534562572b453855496b41 is replaced by UUID a073547e-00b6-4bf9-8e08-5eef08499a9c:
+
----
[root@IBMx3550M3-229-169 ~]# cat /etc/fstab
/dev/VolGroup00/LogVol00 /  ext3  defaults   1 1
LABEL=/boot /boot  ext3     defaults         1 2
tmpfs  /dev/shm    tmpfs    defaults         0 0
devpts /dev/pts    devpts   gid=5, mode=620  0 0
sysfs  /sys	       sysfs           defaults  0 0
proc   /proc       proc           defaults   0 0
/dev/VolGroup00/LogVol01 swap	swap  defaults 0 0
/dev/mapper/test_vg-test_lv /mnt/lvm_ext3 ext3 defaults,_netdev 0 0
UUID=a073547e-00b6-4bf9-8e08-5eef08499a9c /mnt/dmmp_ext3 ext3 defaults,_netdev 0 0
----

*Related information*

xref:task_gathering_pretransition_information_from_inventory_assessment_workbook.adoc[Gathering pretransition information from the Inventory Assessment Workbook]
