---
permalink: san-host/task_testing_transitioned_luns_and_esxi_host_applications_before_cutover.html
sidebar: sidebar
keywords: 
summary: 'If you are using the 7-Mode Transition Tool \(7MTT\) 2.2 or later and Data ONTAP 8.3.2 or later to transition an ESXi host, you can test your transitioned clustered Data ONTAP LUNs to verify that you can bring your host and applications online before the cutover phase. Your source host can continue to run I/O to your source 7-Mode LUNs during testing.'
---
= Testing transitioned LUNs and ESXi host applications before the cutover phase of copy-based transitions
:icons: font
:imagesdir: ../media/

[.lead]
If you are using the 7-Mode Transition Tool (7MTT) 2.2 or later and Data ONTAP 8.3.2 or later to transition an ESXi host, you can test your transitioned clustered Data ONTAP LUNs to verify that you can bring your host and applications online before the cutover phase. Your source host can continue to run I/O to your source 7-Mode LUNs during testing.

* The new test host must be provisioned in a new test environment.
+
To avoid IP/MAC or UUID duplication or conflicts, test hosts must be configured in a private network.

* If you are transitioning a host booted from a local hard disk, the test host must have the same ESXi version and drivers as the source host.
* Zoning must be complete between FC or FCoE hosts and new clustered Data ONTAP nodes.
* Zoning must not exist between the source host and the new clustered Data ONTAP host.
+
If transitioned clustered Data ONTAP LUNs are visible to the source host during test mode, you might experience unexpected service disruptions on the source host.

* If you are transitioning a SAN booted host, your network adapter must be disabled.

You must maintain hardware parity between the test host and the source host and you must perform the following steps on the test host:

Your clustered Data ONTAP LUNs are in read/write mode during testing. They convert to read-only mode when testing is complete and you are preparing for the cutover phase.

. After the baseline data copy is complete, select *Test Mode* in the 7MTT user interface (UI).
. In the 7MTT UI, click *Apply Configuration*.
. Zone the clustered Data ONTAP nodes on the test host.
. Log in to the clustered Data ONTAP node, and then add new test host initiators to the igroup created by the 7MTT during the test phase.
. Navigate to C:\Program Files\NetApp\operating in 7-Mode Transition Tool\.
. Generate the 7-Mode to clustered Data ONTAP LUN mapping file from the Linux host where the 7MTT is installed: `transition cbt export lunmap -p project-name -o file_path`
+
For example: `transition cbt export lunmap -p SanWorkLoad -o c:/Libraires/Documents/7-to-C-LUN-MAPPING.csv`

. Bring the test host online.
 ** xref:concept_reconfiguration_of_vmware_software_iscsi_initiator.adoc[Reconfigure your VMware software iSCSI initiator after transition]
 ** xref:task_setting_up_esxi_hosts_configured_for_san_boot_after_transition.adoc[Set up your ESXi hosts configured for SAN boot after transition]
. Verify that all transitioned clustered Data ONTAP LUNs are discovered.
. If you are transitioning a non-SAN booted host, reregister your VMs.
+
xref:task_reregistering_vms_after_transition_on_non_san_boot_esxi_host_using_vsphere_client.adoc[Re-registering VMs after transition of ESXi host.]

. Complete the necessary post-transition steps for ESXi hosts.
+
xref:concept_post_transition_requirements_for_esxi_hosts.adoc[Post transition requirements for ESXi hosts]

. Bring the host and applications online.
. Perform your testing as needed.
. Shut down the test host.
. In the 7MTT UI, click *Finish Testing*.
+
The new clustered Data ONTAP LUNs are now read-only, and the data from the source 7-Mode LUNs is resynchronized.

. If you plan to use the same source after you complete your transition, then edit the igroup on the clustered Data ONTAP node to add the appropriate initiator.
+
If you are planning to promote your test host to production, then you do not need to edit the igroup.

After you complete your test, plan time to shut down the source host connected to your controllers running Data ONTAP operating in 7-Mode. When you click *Complete Transition*, your source 7-Mode volumes and LUNs go offline and the transitioned clustered Data ONTAP LUNs become read/write.

*Related information*

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html[Copy-based transition]
