---
permalink: san-host/task_preparing_rhel_luns_with_mount_points_using_dmmp_alias_names_for_transition_using_the_cli.html
sidebar: sidebar
keywords: 
summary: 'Before transition of a mount point using a DMMP device name, you must replace the DMMP device name with its respective file system UUID number.'
---
= Preparing RHEL LUNs with mount points using DMMP alias names for transition using the CLI
:icons: font
:imagesdir: ../media/

[.lead]
Before transition of a mount point using a DMMP device name, you must replace the DMMP device name with its respective file system UUID number.

This procedure applies to copy-based transitions and copy-free transitions.

. Identify and record the SCSI device ID for the LUN to be transitioned: `sanlun lun show`
+
The SCSI device ID is listed under the filename column in the output.

. Identify and record the DMMP device name for the LUN to be transitioned: `multipath -ll SCSI_device_ID`
+
In the following example, 360a9800037534562572b453855496b41 is the DMMP device name:
+
----
[root@IBMx3550M3-229-169 ~]# multipath -ll /dev/sdc
dmmp_fs_lun (360a9800037534562572b453855496b41) dm-3 NETAPP, LUN
[size=1.0G] [features=3 queue_if_no_path pg_init_retries 50] [hwhandler=0][rw]
\_ round-robin 0 [prio=2][active]
	\_ 9:0:0:1 sdc 8:32  [active][ready]
	\_ 9:0:0:1 sdg 8:96  [active][ready]
----

. Identify the file system configured on the DMMP device: `blkid | grep -i DMMP_device_name`
+
The TYPE value in the output identifies the file system.
+
In the following example, the file system is ext3.
+
----
[root@ibmx3550-229-108 ~]#blkid | grep -i 3600a09804d532d79565d47617679658
/dev/mapper/3600a09804d532d79565d47617679658:
UUID="450b999a-4f51-4828-8139-29b20d2f8708" TYPE="ext3" SEC_TYPE="ext2"
----

. Identify the UUID number for the LUN: `dumpe2fs device_path_name | grep UUID`
. Identify the directory on which the DMMP device is mounted: `df -h`
+
In the following example, /mnt/dmmp_ext3 represents the directory on which the DMMP device is mounted:
+
----
[root@IBMx3550M3-229-169 ~]# df -h
Filesystem Size Used Avail Use% Mounted on
/dev/mapper/dmmp_fs_lun
1008M 34M 924M 4% /mnt/dmnp_ext3
----

. Verify in the /etc/fstab file that the mount points for the DMMP device are defined: `cat /etc/fstab`
+
The DMMP device name and mount directory should be displayed in the output.

. Create a backup of the /etc/fstab file: `cp /etc/fstab /etc/fstab_pre_transition_bkup`
. Edit the /etc/fstab file to replace the DMMP device name with its respective file system UUID number.
