---
permalink: copy-based/concept_restrictions_for_transition.html
sidebar: sidebar
keywords: ontap, copy, based, transition, restrictions
summary: 'You must be aware of certain restrictions for transitioning some 7-Mode volumes and configurations.'
---
= Restrictions for transition
:icons: font
:imagesdir: ../media/

[.lead]
You must be aware of certain restrictions for transitioning some 7-Mode volumes and configurations.

* No volume within the same project can cut over until all volumes in the same project have completed their baseline transfers.
* If you want to transition 7-Mode primary and secondary volumes when both the 7-Mode source and destination are running Data ONTAP 7.3.x or 8.0.x, you must start transitioning the 7-Mode secondary volume only when there are no data updates from the 7-Mode primary to the 7-Mode secondary volume.
+
You must verify that the data update schedules for the 7-Mode primary volume to the 7-Mode secondary volume do not conflict with the schedules for the 7-Mode secondary volume to the ONTAP secondary volume.

* You must not initiate a transition while the aggregates on either the 7-Mode system or cluster are upgrading from 32-bit to 64-bit format; otherwise the transition fails.
* The 7-Mode Transition tool does not transition a volume with a qtree that is the destination of a qtree SnapMirror relationship.
+
The qtree SnapMirror relationship must be broken before the volume can be transitioned.

* You cannot transition a fanout SnapMirror relationship (a primary volume that is in SnapMirror relationships with more than one secondary volume in different controllers) by using the 7-Mode Transition Tool web interface.
+
To transition the SnapMirror relationships in a fanout configuration, you must use the 7-Mode Transition Tool CLI. You should create separate projects for each secondary volume, complete the transition of the secondary projects, and then create and complete the transition of the primary volume.

* You cannot transition volumes from different vFiler units or from different 7-Mode controllers to the same SVM at the same time.
+
You must complete the transition of volumes from a given vFiler unit or 7-Mode controller before you can start the transition of volumes from another vFiler unit or 7-Mode controller.

* The 7-Mode Transition tool does not transition a vFiler unit as a single entity.
+
However, you can transition all of the volumes in a vFiler unit by selecting them as a part of one or more projects.

* The 7-Mode Transition tool does not transition the root volume of a vFiler unit if the root volume is based on a qtree that belongs to the default vFiler unit.
* The 7-Mode Transition tool does not transition a volume with a qtree if the volume and qtree are owned by different vFiler units.
+
Transitioning such a volume causes the qtree to become inaccessible.

* Transitioned volumes cannot be converted to FlexGroup volumes.

The precheck operation displays information about some of these restrictions.
