---
permalink: copy-based/concept_prerequisites_to_transition_nfs_configurations.html
sidebar: sidebar
keywords: ontap, copy, based, transition, prerequisites, nfs, configurations
summary: 'NFS configurations are transitioned by the 7-Mode Transition Tool only when certain prerequisites are met on the 7-Mode system and the cluster. If any of the conditions are not met, the tool does not transition the configuration.'
---
= Prerequisites for transitioning NFS configurations
:icons: font
:imagesdir: ../media/

[.lead]
NFS configurations are transitioned by the 7-Mode Transition Tool only when certain prerequisites are met on the 7-Mode system and the cluster. If any of the conditions are not met, the tool does not transition the configuration.

== 7-Mode prerequisites

* NFS must be licensed.
* If MultiStore is licensed, NFS must be enabled on the vFiler unit that owns the transitioning volumes.
* For transitioning a Microsoft Active Directory (AD) based Kerberos server to a new SVM, a DNS entry must exist for the AD domain.
+
NOTE: To transition the Kerberos configuration, at least one LIF must be transitioned as part of the project and the LIF must be resolvable to a host name.

* If you want to transition in-memory export rules, you must add them to the `/etc/exports` file before transition.
+
The 7-Mode Transition Tool transitions only the persistent export rules that are defined in the `/etc/exports` file.

== Cluster prerequisites

* NFS must be licensed.
* For transitioning a Microsoft AD-based Kerberos server to an existing SVM with DNS configured, a DNS entry must exist for the AD domain.
* The clock skew between the Kerberos key distribution center (KDC) and the ONTAP system must be less than or equal to 5 minutes.

*Related information*

xref:concept_how_nfs_exports_are_transitioned.adoc[How NFS exports are transitioned]

http://docs.netapp.com/ontap-9/index.jsp[NetApp Documentation: ONTAP 9]
