---
permalink: copy-based/task_creating_a_transition_session.html
sidebar: sidebar
keywords: ontap, copy, based, transition, create, project
summary: 'You can create a transition project that identifies the 7-Mode objects to be transitioned and how they map to the ONTAP objects. While creating the project, the 7-Mode Transition Tool collects and saves the information about the transition objects. You can use this project information to perform the transition in stages.'
---
= Creating a transition project
:icons: font
:imagesdir: ../media/

[.lead]
You can create a transition project that identifies the 7-Mode objects to be transitioned and how they map to the ONTAP objects. While creating the project, the 7-Mode Transition Tool collects and saves the information about the transition objects. You can use this project information to perform the transition in stages.

You must have gathered the following information:

* Project type: Possible values are stand-alone, primary, or secondary
* FQDN or IP address of the 7-Mode storage system or the default vFiler unit, if MultiStore is licensed
* Administrative user name and password of the 7-Mode storage system
* List of 7-Mode volumes
* FQDN of the cluster or IP address of the cluster-management LIF
* SVM name

.Steps
. From the *Start* menu, click *All Programs* > *NetApp 7-Mode Transition Tool* > *NetApp 7-Mode Transition Tool (CLI) 3.0* to open the 7-Mode Transition Tool command prompt.
. Add the user name and password of the systems that are a part of the transition project:
+
`*transition credentials add -h _host_name_ -u _user_name_*`
+
`_host_name_` is FQDN or IP address of the 7-Mode system or cluster.
+
`_user_name_` is the administrative user name for the system.
+
NOTE: You must repeat this step for each storage system that you want to add to the transition projects.
+
----
7-Mode Transition Tool>transition credentials add -h system1.example.com -u root
Enter password for 'root@system1.example.com':
----

. Create a transition project:
+
`*transition cbt create -p _project_name_ -t _project_type_ -n _7-Mode_system_ -c _data-copy-ipaddress_ [-f _vfiler_name_] [-h _cluster_ -v _vserver_name_*`
+
`_project_name_` is the name of the transition project.
+
`_project_type_` is the project type. Valid values are standalone, secondary, or primary.
+
`_7-Mode_system_` is the FQDN or IP address of the 7-Mode system.
+
`_cluster_` is the FQDN of the cluster or IP address of the cluster-management LIF.
+
NOTE: The host names of your 7-Mode system and cluster must be the same as those you had provided while creating the project.
+
`_data-copy-ipaddress_` is the IP address over which data is copied.
+
`_vfiler_name_` is the name of the nondefault vFiler unit.
+
`_vserver_name_` is the name of the SVM.
+
NOTE: For a new SVM, you must provide the aggregate name of the root volume of the SVM with the `-g` option.
+
----
7-Mode Transition Tool>transition cbt create -p sample_project -t standalone -n system1.example.com -n 10.238.55.33 -h cluster1.example.com -v vs2
----
+
The transition project moves to the preparation state.

. Add the 7-Mode volume and ONTAP volume to the project:
+
`*transition cbt volumepair add -p _project_name_ -v _7-Mode_volume_ -c _vserver_volume_ -g _aggr_name_ -t*`
+
`_7-Mode_volume_` is the 7-Mode volume name.
+
`_vserver_volume_` is the ONTAP volume on the SVM.
+
NOTE: You can also add an ONTAP volume for which the baseline transfer has been completed. When you add such a volume in the preparation phase, only incremental transfers are performed during the data copy phase.
+
`_aggr_name_` is the aggregate on which the ONTAP volume `_vserver_volume_` is created during the start operation.
+
`_-t_` is used when a volume which is in SnapMirror relationships must be transitioned as standalone volume.
+
NOTE: When a volume is transitioned as standalone volume, SnapMirror relationships are not preserved during the transition.
+
For SnapLock Compliance volumes that are in SnapMirror relationship, the transition of SnapMirror relationships for SnapLock Compliance volumes is not automated by the 7-Mode Transition Tool. All SnapLock Compliance volumes that are in SnapMirror relationship must be transitioned as standalone volumes (by specifying the flag -t) by including the volumes in standalone, primary, or secondary projects. You must then manually perform the SnapMirror resychronization operation between these volumes after the transition.
+
See xref:concept_considerations_for_transitioning_of_snaplock_compliance_volumes.adoc[Considerations for transitioning of SnapLock Compliance volumes]
+
----
7-Mode Transition Tool>transition cbt volumepair add -p sample_project -v vol1 -c vol1 -g aggr1
----

. Add the IP addresses to be transitioned to the project:
+
`*transition cbt lif add -p _project_name_ -i _ip-address_ [-m _netmask_] [-g _default-gateway_] [-p _home_port_] [ -n _home_node_]*`
+
To a transition project, you can also add existing IP addresses that are unconfigured or removed from the 7-Mode system during storage cutover, and new IP addresses that are not yet configured on either the 7-Mode or ONTAP.
+
NOTE: FC and iSCSI LIFs are not transitioned by the 7-Mode Transition Tool.
+
----
7-Mode Transition Tool>transition cbt lif add -p sample_project -i 192.0.2.250 -m 255.255.255.128 -g 192.40.0.1 -p e0a -n cluster1-01
----
+
The new IP addresses are configured on the ONTAP system in the up state during the apply configuration (precutover) operation.

. Follow these steps to add information to the primary and secondary project:
+
[options="header"]
|===
| If you want to add information about the...| Enter...
a|
Primary 7-Mode system to the secondary project
a|
`*transition cbt add-primary-seven-mode-system -p _project_name_ -h _source-host_ -f _management-ipaddress_ -d _data-copy-ipaddress_ [-m _multipathing-ipaddress_]*`

For more information, see https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/CBT_%3A_How_to_provide_all_the_required_primary_7-Mode_details_for_a_given_secondary_project[CBT : How to provide all the required primary 7-Mode details for a given secondary project].
a|
Secondary cluster or SVM to the primary project
a|
`*transition cbt add-secondary-cluster-mode-system -p _project_name_ -h _c-mode-host-name_ -v _vserver-name_*`

For more information, see the https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/CBT%3A_How_to_add_the_required_secondary_cluster_details_to_the_primary_project[CBT: How to add the required secondary cluster details to the primary project]

|===
`_project_name_` is the name of the transition project.
+
`_source-host_` is the primary 7-Mode storage system host name or IP address as seen in the `snapmirror status` command output of the secondary 7-Mode system.
+
For considerations about providing the 7-Mode primary system details, see the man pages.
+
`_management-ipaddress_` is the management IP address of the source host.
+
`_data-copy-ipaddress_` is the IP address over which data is copied.
+
`_multipathing-ipaddress_` is the additional IP address that is used for data copy.
+
`_c-mode-host-name_` is the FQDN or IP address of the cluster to which the secondary volumes in the project have been transitioned.
+
`_vserver-name_` is the name of the SVM hosting the secondary volumes.

. Create a data copy schedule:
+
`*transition cbt schedule add -p _project_name_ -n _schedule_name_ -d _days-range_ -b _start-time_ -e _duration_ -u _update-frequency_ -t _available-transfers-percentage_ -c _max-cap-concurrent-transfers_ -x _project-snapmirror-throttle_*`
+
The following command shows how to add a schedule that uses 100% of available concurrent SnapMirror transfers. However, it does not exceed the 25 concurrent SnapMirror transfers at any point of time.
+
`*transition schedule add -p sample_project -n dr_active -d 1-5 -b 23:30 -e 03:00 -c 25 -x 200 -u 00:30*`

. View the detailed information about the transition project created:
+
`*transition cbt show -p _project-name_*`
