---
permalink: copy-based/task_preparing_7_mode_system_for_transition.html
sidebar: sidebar
keywords: ontap, copy, based, transition, prepare, 7, mode
summary: 'Before starting a transition, you must complete certain tasks on the 7-Mode system, such as adding the SnapMirror license, enabling the 7-Mode system to communicate with the target cluster, and enabling TLS.'
---
= Preparing the 7-Mode system for transition
:icons: font
:imagesdir: ../media/

[.lead]
Before starting a transition, you must complete certain tasks on the 7-Mode system, such as adding the SnapMirror license, enabling the 7-Mode system to communicate with the target cluster, and enabling TLS.

All the 7-Mode volumes that you want to transition must be online.

.Steps
. Add and enable the SnapMirror license on the 7-Mode system:
 .. Add the SnapMirror license on the 7-Mode system:
+
`*license add _license_code_*`
+
`_license_code_` is the license code you purchased.

 .. Enable the SnapMirror functionality:
 +
 `*options snapmirror.enable on*`
. Configure the 7-Mode system and the target cluster to communicate with each other by choosing one of the following options:
 ** Set the `snapmirror.access` option to all.
 ** Set the value of the `snapmirror.access` option to the IP addresses of all the intercluster LIFs on the cluster.
 ** If the `snapmirror.access` option is `legacy` and the `snapmirror.checkip.enable` option is `off`, add the SVM name to the `/etc/snapmirror.allow` file.
 ** If the `snapmirror.access` option is `legacy` and the `snapmirror.checkip.enable` option is `on`, add the IP addresses of the intercluster LIFs to the `/etc/snapmirror.allow` file.
. If HTTPS is not enabled on the storage system, enable HTTPS:
+
`*options httpd.admin.ssl.enable on*`
+
HTTPS is enabled by default.

. Enable TLS on the 7-Mode storage systems for enabling the 7-Mode Transition Tool to communicate with the 7-Mode systems:
 .. If SSL is not already enabled on the storage system, set up and start SSL:
+
`*secureadmin setup ssl*`
+
SSL is set up for the storage systems by default. If SSL has been previously set up for the storage system, you are asked whether you want to continue. You can exit the SSL setup if you do not want to make any changes.

 .. Enable SSL:
+
`*options ssl.enable on*`
+
This option must be enabled for allowing communication over TLS.

 .. Enable TLS:
+
`*options tls.enable on*`
 .. Disable SSLv2 and SSLv3 on the 7-Mode system:
+
`*options ssl.v2.enable off*`
+
`*options ssl.v3.enable off*`

+
The 7-Mode Transition Tool uses TLS or SSL protocols for communicating with the 7-Mode storage systems. The tool communicates with the storage system using the TLS protocol if TLS is enabled on the storage system. If TLS is disabled and SSLv3 is enabled on a storage system, the tool uses SSLv3 to communicate with the storage system.
+
IMPORTANT: The best practice is to enable TLS and disable SSLv2 and SSLv3 in order to avoid security vulnerabilities.
. Depending on the Data ONTAP version of your 7-Mode system, perform the following steps:
 .. Allow SnapMirror traffic on all the interfaces:
+
`*options interface.blocked.snapmirror ""*`
 .. If you are running Data ONTAP version 7.3.7, 8.0.3, or 8.1 and you are using the IP address of the e0M interface as the management IP address to interact with 7-Mode Transition Tool, allow data traffic on the e0M interface:
+
`*options interface.blocked.mgmt_data_traffic off*`
. If you have set the I2P, read allocations, or NVFAIL options on the volume, perform the following steps:
 .. Verify that other operations are not impacted if these options are disabled.
 .. Disable the options:
+
`*vol options vol_name no_i2p off*`
+
`*vol options vol_name read_realloc off*`
+
`*vol options vol_name nvfail off*`
