---
permalink: copy-based/task_completing_transition_process.html
sidebar: sidebar
keywords: ontap, copy, based, transition, complete
summary: 'Because the complete operation is disruptive, you should evaluate when to run it. When transitioning volumes in a SnapMirror relationship, the secondary project must be completed before completing the transition of the primary project.'
---
= Completing the transition
:icons: font
:imagesdir: ../media/

[.lead]
Because the complete operation is disruptive, you should evaluate when to run it. When transitioning volumes in a SnapMirror relationship, the secondary project must be completed before completing the transition of the primary project.

.Steps
. Perform a data copy from the 7-Mode volumes to the ONTAP volumes:
+
`*transition cbt update -p _project_name_ -t _available-transfers-percentage_ -c _snapmirror-throttlemax-cap-concurrent-transfers_ -x -r interactive*`
+
This helps in reducing the downtime during storage cutover.

. Manual: Disconnect client access.
. Complete the transition process:
+
`*transition cbt cutover -p _project_name_ -t _available-transfers-percentage_ -c _max-cap-concurrent-transfers_ -x _snapmirror-throttle_ -r interactive -o [true|false]*`
+
By default, the 7-Mode volumes are made offline. To keep the 7-Mode volumes online, set the `-o` option to `false`.
+
NOTE: If the cutover is not successful for some reason--for example, the 7-Mode system or cluster is not reachable--you must resolve the issues and run the `transition cutover` command again.
+
For more information about the commands, see the man pages.
+
The transition session moves to the cutover state. If the cutover is successful, the session moves to the completed state.

You must perform any post-transition tasks and reconnect the clients to the ONTAP volumes.
