---
permalink: copy-based/task_completing_chain_of_custody_verification.html
sidebar: sidebar
keywords: ontap, copy, based, transition, complete, chain, custody, verification
summary: 'If one or more SnapLock volumes are selected for Chain of Custody verification, then you must perform the Chain of Custody operation to generate a Chain of Custody report.'
---
= Completing the Chain of Custody verification
:icons: font
:imagesdir: ../media/

[.lead]
If one or more SnapLock volumes are selected for Chain of Custody verification, then you must perform the Chain of Custody operation to generate a Chain of Custody report.

You must have completed the transition of the project.

SnapLock Chain of Custody operation is supported for volumes with files that have file names with only ASCII characters.

. From the Migration Dashboard, click *Start Chain of Custody*.
+
If you want to keep the 7-Mode SnapLock volumes online after the Chain of Custody verification, you should clear the *Take 7-Mode SnapLock volumes selected for Chain of Custody verification offline after Chain of Custody verification operation is completed* check box.

. Click *Continue*.
+
The Chain of Custody verification operation is initiated. This operation can take a significant amount of time based on the number of files on the SnapLock volumes. You can click *Run in Background* to perform the operation in the background.
+
You can track the progress of the Chain of Custody verification operation by clicking the SnapLock Chain of Custody tab in the Migration Dashboard window. This tab displays per volume progress of the Chain of Custody operation.

. After the Chain of Custody operation is complete, click *Download Report* in the SnapLock Chain of Custody tab to download the Chain of Custody verification report.
+
The Chain of Custody verification report contains details about whether the SnapLock Chain of Custody verification succeeded. The report shows the total file count and the number of non-WORM files in each of the 7-Mode SnapLock volumes that are selected for the Chain of Custody operation. You can also verify the number of files for which the fingerprints matched and unmatched. The report also shows the number of WORM files for which the Chain of Custody verification failed and reason for the failure.
