---
settings:
  name: ONTAP 7-Mode Transition
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: 7-Mode Transition
      url: /index.html
    - title: Release Notes
      url: /releasenotes.html
    - section: command-map
    - section: install-admin
    - section: copy-based
    - section: copy-free
    - section: inventory-collect
    - section: snapmirror
    - section: san-host
    - title: Legal notices
      url: /reference_legal_notices.html
      
product-family: 
  name: ONTAP
  repo: ontap-family
  
