---
settings:
  name: ONTAP 7-Mode Transition
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: 7-Mode Transition
      url: /index.html
    - title: Release Notes
      url: /releasenotes.html
    - section: command-map
    - section: install-admin
    - section: copy-based
    - section: copy-free
    - section: inventory-collect
    - section: snapmirror
    - section: san-host
    - title: Legal notices
      url: /reference_legal_notices.html

homepage:
  tiles:
    - title: Get started
      links:
        - title: What's new
          summary: See what's new in the latest version of the 7-Mode Transition Tool
          url: releasenotes.html
        - title: Install the 7-Mode Transition Tool
          summary: Learn how to install the tool on Microsoft Windows or Linux
          url: /install-admin/concept_transition_to_clustered_ontap_using_7mtt.html
        - title: Collect data needed for transition
          summary: Discover how to collect information essential to your transition
          url: /inventory-collect/concept_collecting_host_and_storage_inventory_information_for_transition_assessment.html
    - title: Command map for 7-mode administrators
      links:
        - title: How 7-Mode commands map to ONTAP commands
          summary: Find the ONTAP equivalents of 7-Mode commands
          url: /command-map/reference_how_7_mode_commands_map_to_clustered_ontap_commands.html
        - title: How 7-Mode options map to ONTAP commands
          summary: Learn how 7-Mode options map to ONTAP command parameters
          url: "/command-map/reference_how_7_mode_options_map_to_clustered_ontap_commands.html"
        - title: How 7-Mode configuration files map to ONTAP commands
          summary: Lean how 7-Mode configuration files map to ONTAP configuration commands
          url: "/command-map/reference_how_7_mode_configuration_files_map_to_clustered_ontap_commands.html"
    - title: Ways to transition
      links:
        - title: Copy-based transition
          summary: Use the tool to perform a copy-based transition  from 7-Mode to ONTAP
          url: /copy-based/concept_copy_based_transition_workflow.html
        - title: Copy-free transition
          summary: Use the tool to perform a copy-free transition  from 7-Mode to ONTAP
          url: /copy-free/task_copy_free_transition_workflow.html
        - title: Transition data using SnapMirror
          summary: Understand how to transition data from 7-Mode to ONTAP using SnapMirror commands
          url: /snapmirror/task_transitioning_7_mode_volumes_using_snapmirror.html
    - title: SAN host transition and remediation
      links:
        - title: VMware ESXi
          summary: Understand the pre- and post-transition requirements for VMware ESXi hosts
          url: /san-host/concept_vmware_esxi_host_remediation.html
        - title: Red Hat Enterprise Linux
          summary: Understand the pre- and  post-transition requirement for Red Hat Enterprise Linux hosts
          url: /san-host/concept_linux_host_remediation.html
        - title: Windows
          summary: Understand the pre- and post-transition steps for Microsoft Windows hosts 
          url: /san-host/concept_windows_host_remediation.html

