---
permalink: install-admin/concept_comparison_of_copy_free_transition_and_copy_based_transition.html
sidebar: sidebar
keywords: 
summary: 'You can use the 7-Mode Transition Tool to migrate your data and configurations from 7-Mode to ONTAP by using either copy-based transition or copy-free transition. It is important to understand the differences between the two methods before transition.'
---
= Comparison of copy-free transition and copy-based transition
:icons: font
:imagesdir: ../media/

[.lead]
You can use the 7-Mode Transition Tool to migrate your data and configurations from 7-Mode to ONTAP by using either copy-based transition or copy-free transition. It is important to understand the differences between the two methods before transition.

|===
| Parameter| Copy-free transition| Copy-based transition
a|
Unit of transition
a|
HA pair
a|
Group of volumes
a|
Hardware requirement
a|
Disk shelves are reused
a|
New disks shelves and disks to host the transitioned volumes
a|
Platform requirement
a|
Supported only on mid-level and high-level platforms https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]

a|
Supported on all platforms
a|
Transition duration
a|
Overall, shorter transition duration (no data copy required)
a|
Longer duration (initial baseline and update transfer time varies based on workload, network bandwidth, and data capacity being migrated)
a|
Disruption to data access
a|
In the range of hours *Important:* In most cases, the storage cutover time can be 3 through 8 hours. Cutover time includes the time taken by the tool to perform two automated operations--the export and halt operation and the import operation--as well as the time taken for manually cabling the disk shelves to the new controllers. The export and halt operation and the import operation together can take up to 2 hours. Cabling of the disk shelves can take from 1 hour through 6 hours.

This cutover time guidance does not include the time taken for the required preproduction testing and assumes an error-free transition without unexpected failures such as a disk failure.

a|
In the range of minutes
|===
