---
permalink: install-admin/task_logging_in_to_tool.html
sidebar: sidebar
keywords: ontap, 7, mode, install, login, transition, tool
summary: 'You can log in to the 7-Mode Transition Tool \(web interface\) by using your credentials of the Windows system on which the tool is installed. The procedure to log in varies depending on the type of user credentials you have.'
---
= Logging in to the 7-Mode Transition Tool
:icons: font
:imagesdir: ../media/

[.lead]
You can log in to the 7-Mode Transition Tool (web interface) by using your credentials of the Windows system on which the tool is installed. The procedure to log in varies depending on the type of user credentials you have.

Guest users are not allowed to log in to the tool.

.Steps
. Navigate to the login page:
+
[options="header"]
|===
| If you are a...| Then...
a|
User who is a member of the Administrator group and if you are accessing the tool (web interface) from the server on which it was installed
a|
Double-click the 7-Mode Transition Tool icon on your desktop.
a|
User who is a member of the Administrator group and if you have not installed the tool
a|
Use a supported browser to navigate to one of the following URLs:

 ** `https://_IP_address:port_/transition`
 ** `http://_IP_address:port_/transition`
`_IP_address_` is the IP address of the server and `_port_` can be 8443 (default), the value specified for `_tool.https.port_`, or 8088, the value specified for the `_tool.http.port_` parameter in the `_transition-tool.conf_` file.

a|
User who is a member of the Administrator group and if you are accessing the tool (web interface) from another computer
a|
Use a supported browser to navigate to one of the following URLs:

 ** `https://_IP_address:port_/transition`
 ** `http://_IP_address:port_/transition`
`_IP_address_` is the IP address of the server and port can be 8443 (default), the value specified for `_tool.https.port_`, or 8088, the value specified for the `_tool.http.port_` parameter in the `_transition-tool.conf_` file.

a|
User who is not a member of the Administrator group and if you are accessing the tool (web interface) either from the server on which it was installed or from another computer
a|
Use a supported browser to navigate to one of the following URLs:

 ** `https://_IP_address:port_/transition`
 ** `http://_IP_address:port_/transition`
`_IP_address_` is the IP address of the server and port can be 8443 (default), the value specified for the `_tool.https.port_`, or 8088, the value specified for the `_tool.http.port_` parameter in the `_transition-tool.conf_` file.

+
|===

. If the browser displays a message about the self-signed SSL certificate, then accept the self-signed certificate to continue.
. Log in to the web interface by using the credentials of the Windows system in which the tool is installed.
