---
permalink: inventory-collect/concept_collecting_host_and_storage_inventory_information_for_transition_assessment.html
sidebar: sidebar
keywords: ontap, 7, mode, transition, collect, storage, host, inventory, information
summary: 'Inventory Collect Tool enables you to collect information about clustered Data ONTAP and 7-Mode systems, switches, hosts, and the applications running on these hosts and to create an inventory report. You can then import the inventory report to the 7-Mode Transition Tool for transition assessment.'
---
= Collecting storage and host inventory information
:icons: font
:imagesdir: ../media/

//
//update release notes to github link
//

[.lead]
Inventory Collect Tool enables you to collect information about clustered Data ONTAP and 7-Mode systems, switches, hosts, and the applications running on these hosts and to create an inventory report. You can then import the inventory report to the 7-Mode Transition Tool for transition assessment.

The tool generates an inventory report workbook and an inventory report XML file that contain configuration details of the storage and host systems.

The Inventory Collect Tool uses TLS or SSL protocols for communicating with the 7-Mode storage systems and SSH or WMI for communicating with hosts. The tool communicates with the storage system using the TLS protocol if TLS is enabled on the storage system. If TLS is disabled and SSLv3 is enabled on a storage system, the tool uses SSLv3 to communicate with the storage system.

NOTE: The best practice is to enable TLS and disable SSLv3 on the storage system in order to avoid SSLv3 security vulnerabilities (CVE-2014-3566).

If you cannot install the 7-Mode Transition Tool in your environment due to security reasons, then you can import the inventory report XML file generated by the Inventory Collect Tool to 7-Mode Transition Tool (installed outside your data center) for generating an assessment report. You can use the assessment report for assessing the features and functionalities of your systems and identify how these features and functionalities work in the clustered Data ONTAP version selected for transition.

Inventory Collect Tool is a stand-alone utility that does not require any installation.

Be sure to consult the current 7-Mode Transition Tool link:http://docs.netapp.com/us-en/ontap-7mode-transition/releasenotes.html[Release Notes] for the latest information about supported target releases and known issues.
