---
permalink: command-map/concept_how_to_interpret_the_7_mode_to_clustered_data_ontap_commands_options_and_configuration_files_maps.html
sidebar: sidebar
keywords: 
summary: 'If you are moving from Data ONTAP running in 7-Mode to clustered Data ONTAP, you might find it handy to refer to the command maps, which show the clustered Data ONTAP equivalents of 7-Mode commands, options, and configuration files.'
---
= How to interpret the clustered Data ONTAP commands, options, and configuration files maps for 7-Mode administrators
:icons: font
:imagesdir: ../media/

[.lead]
If you are moving from Data ONTAP running in 7-Mode to clustered Data ONTAP, you might find it handy to refer to the command maps, which show the clustered Data ONTAP equivalents of 7-Mode commands, options, and configuration files.

== What mapping information is included

The Command Map for 7-Mode Administrators includes the following mappings of 7-Mode commands, options, and configuration files to their clustered Data ONTAP equivalents:

* xref:reference_7_mode_to_clustered_data_ontap_command_map.adoc[How 7-Mode commands map to clustered Data ONTAP commands]
* xref:reference_how_7_mode_options_map_to_ontap_commands.adoc[How 7-Mode options map to clustered Data ONTAP commands]
* xref:reference_how_7_mode_configuration_files_map_to_clustered_data_ontap_commands.adoc[How 7-Mode configuration files map to clustered Data ONTAP commands]

== How to interpret 7-Mode-compatible shortcut commands

Although the Data ONTAP command-line interface (CLI) is significantly reorganized for cluster operations, many of the commands have 7-Mode-compatible shortcut versions that require no change to scripts or other automated tasks. These shortcut versions are listed first and in *bold* in the tables here. Shortcut versions that are not 7-Mode-compatible are listed next, followed by the full, long-form version of the commands:

|===
| 7-Mode command| Clustered Data ONTAP command
a|
aggr add
a|
*aggr add* aggr add-disks

storage aggregate add-disks

|===
If no *bold* shortcut is listed, a 7-Mode-compatible version is not available. Not all forms of the commands are shown in the table. The CLI is extremely flexible, allowing multiple abbreviated forms.

== Understanding the different clustered Data ONTAP shells for CLI commands

A cluster has three different shells for CLI commands:

* The clustershell is the native shell, started automatically when you log in to the cluster.
+
It provides all the commands you need to configure and manage the cluster.

* The nodeshell is a special shell that enables you to run a subset of 7-Mode commands.
+
These commands take effect only at the node level. You can switch from the clustershell to a nodeshell session to run nodeshell commands interactively, or you can run a single nodeshell command from the clustershell. You can recognize a command as a nodeshell command if it has the (long) form `system node run -node {nodename|local} commandname`.

* The systemshell is a low-level shell used only for diagnostic and troubleshooting purposes.
+
It is not intended for general administrative purposes. Access the systemshell only with guidance from technical support.

== Switching to nodeshell

When you see a 7-Mode-compatible shortcut version of a nodeshell command, it is assumed that you are running the command from the nodeshell. To switch to the nodeshell, enter the following:

`system node run -node {nodename|local}`

Other forms of the nodeshell command must be run from the clustershell.

== Where to go for more information

|===
| If you want to...| For more information...
a|
Use clustershell commands
a|
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html[ONTAP 9 commands]
a|
Use nodeshell commands
a|
https://library.netapp.com/ecm/ecm_download_file/ECMP1511537[Data ONTAP 8. 2 Commands: Manual Page Reference for 7-Mode, Volume 1]
a|
Execute CLI commands, navigate CLI command directories, set values in the CLI, and use queries, patterns, and wildcards
a|
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/home.html[System administration]
|===
