---
permalink: copy-free/concept_when_to_revert_and_when_to_call_technical_support_transition.html
sidebar: sidebar
keywords: 
summary: 'You can roll back without assistance when performing a rollback on test or lab clusters, but you must call technical support if you encounter problems during or after transition, or if you want to roll back a transition performed on a production cluster.'
---
= When to roll back a transition and when to call technical support
:icons: font
:imagesdir: ../media/

[.lead]
You can roll back without assistance when performing a rollback on test or lab clusters, but you must call technical support if you encounter problems during or after transition, or if you want to roll back a transition performed on a production cluster.

IMPORTANT: You should not attempt to roll back a transition in a production environment without assistance from technical support.

If you encounter any of the following circumstances, contact technical support immediately:

* The transition process fails and cannot finish, and you are unsure of what to do next.
* The transition process finishes, but the cluster is unusable in a production environment.
* The transition process finishes and the cluster goes into production, but you are not satisfied with its behavior.
* The transition process finishes for some but not all of the data and configuration, and you decide that you want to roll back the transition.
* You have a problem with the transition process and cannot resolve the problem with the error response messages in the 7-Mode Transition Tool, in the Data ONTAP EMS event messages, and NetApp Knowledgebase.
+
https://kb.netapp.com/[NetApp Knowledgebase]

*Related information*

xref:task_collecting_tool_logs.adoc[Downloading transition log files]
