---
permalink: copy-free/concept_prerequisites_to_transition_nfs_configurations.html
sidebar: sidebar
keywords: ontap, transition, copy, free, prerequisites, nfs, configurations
summary: 'NFS configurations are transitioned by the 7-Mode Transition Tool only when certain prerequisites are met on the 7-Mode system and the cluster. If any of the conditions are not met, the tool does not transition the configuration.'
---
= Prerequisites for transitioning NFS configurations
:icons: font
:imagesdir: ../media/

[.lead]
NFS configurations are transitioned by the 7-Mode Transition Tool only when certain prerequisites are met on the 7-Mode system and the cluster. If any of the conditions are not met, the tool does not transition the configuration.

== 7-Mode prerequisites

* NFS must be licensed.
* If MultiStore is licensed, NFS must be enabled on all of the vFiler units.
* NFS service must be running on the 7-Mode systems during transition.
+
Even after client access is disconnected and you prepare to start the export phase, the service must be running on the 7-Mode systems.

* If you want to transition in-memory export rules, you must add them to the `/etc/exports` file before transition.
+
The 7-Mode Transition Tool transitions only the persistent export rules that are defined in the `/etc/exports` file.

== Cluster prerequisites

* NFS must be licensed.

*Related information*

http://docs.netapp.com/ontap-9/index.jsp[NetApp Documentation: ONTAP 9]
