---
permalink: copy-free/concept_prerequisites_for_transitioning_cifs_configurations.html
sidebar: sidebar
keywords: ontap, transition, copy, free, cifs, configurations, prerequisites
summary: 'CIFS configurations are transitioned by the 7-Mode Transition Tool only when certain prerequisites are met on the 7-Mode system and cluster. If any of the conditions are not met, the tool does not transition the configuration.'
---
= Prerequisites for transitioning CIFS configurations
:icons: font
:imagesdir: ../media/

[.lead]
CIFS configurations are transitioned by the 7-Mode Transition Tool only when certain prerequisites are met on the 7-Mode system and cluster. If any of the conditions are not met, the tool does not transition the configuration.

== 7-Mode prerequisites

* The CIFS license must be added.
* If the MultiStore license is enabled, CIFS must be added to the list of allowed protocols for the vFiler unit that owns the transitioning volumes.
* CIFS must be set up and running during transition.
+
Even after client access is disconnected and you prepare to start the export phase, the CIFS service must be running on the 7-Mode systems.

* The authentication type for CIFS must be Active Directory (AD) or Workgroup.

== Cluster prerequisites

* The CIFS license must be added.
* The following CIFS authentication methods are supported in different ONTAP versions:
 ** Clustered Data ONTAP 8.2.x and 8.3.x support AD authentication.
 ** ONTAP 9.0 or later supports AD authentication and Workgroup authentication.
* The following table identifies which authentication method must be used on the target SVM:
+
[options="header"]
|===
| 7-Mode authentication method| Clustered Data ONTAP 8.2.x and 8.3.x authentication method| ONTAP 9.5 or earlier authentication method
a|
AD
a|
AD
a|
AD
a|
Workgroup
a|
AD
a|
Workgroup or AD
|===

* You can transition the CIFS configuration from 7-Mode to ONTAP if the AD domains do not match between the 7-Mode CIFS server and the target SVM CIFS server.
+
The tool triggers an ignorable blocking error when an AD domain name mismatch is detected. To proceed with the transition, you can acknowledge the blocking error.

* The CIFS server must be manually configured before the apply configuration (precutover) phase.
+
You can create the CIFS server on the SVM in the following two ways:
+
[options="header"]
|===
| If you want to...| Do the following...
a|
Transfer or preserve the CIFS server identity to the target SVM
a|
    You have the following two options to create the CIFS server:

 .. Applicable for all versions of ONTAP:
  *** Before the SVM provision phase, you must reconfigure the CIFS server on the 7-Mode system system by using a temporary CIFS identity.
+
This reconfiguration allows the original CIFS server identity to be configured on the SVM. You must verify that the CIFS server is running on the 7-Mode system during the "`SVM Provision`" and "`Export & Halt`" phases with the new temporary identity. This action is required to read CIFS configurations from 7-Mode during the SVM Provision and "`Export & Halt`" phases.

  *** You must configure the CIFS server on the target SVM with the original 7-Mode CIFS identity.
  *** After these conditions are met, you can perform the "`SVM Provision`" operation, and then perform the "`Export & Halt`" operation to enable client access to ONTAP volumes.
 .. Applicable for ONTAP releases 9.0 through 9.5:
  *** Use the `vserver cifs modify` command to change the CIFS server name (CIFS Server NetBIOS Name).
+
Using this feature, you should create a CIFS server on the target SVM with a temporary identity, and then perform the "`SVM Provision`" operation.

  *** After the "`import`"' phase, you can run the `vserver cifs modify` command on the target cluster to replace the target SVM CIFS identity with the 7-Mode CIFS identity.

a|
Use a new identity
a|

 ** Before the "`SVM Provision`" phase, you must configure the CIFS server on the target SVM with a new CIFS identity.
 ** You must verify that the CIFS server is up and running on the 7-Mode system during the "`SVM Provision`" and "`Export & Halt`" phases.
+
This action is required to read CIFS configurations from 7-Mode during the "`SVM Provision`"and "`Export & Halt`".

 ** After verifying these conditions, you can perform the "`SVM Provision`" operation.
+
You can then test the SVM configurations, and then plan to perform the storage cutover.

+
|===
