---
permalink: copy-free/concept_considerations_for_space_when_transitioning_san_volumes.html
sidebar: sidebar
keywords: 
summary: 'You must ensure that sufficient space is available in the volumes during transition. In addition to the space required for storing data and Snapshot copies, the transition process also requires 1 MB of space per LUN for updating certain filesystem metadata.'
---
= Space considerations when transitioning SAN volumes
:icons: font
:imagesdir: ../media/

[.lead]
You must ensure that sufficient space is available in the volumes during transition. In addition to the space required for storing data and Snapshot copies, the transition process also requires 1 MB of space per LUN for updating certain filesystem metadata.

You can use the df -h command on the 7-Mode volume to verify whether free space of 1 MB per LUN is available in the volume. The volume should also have free space equivalent to the amount of data that is expected to be written to the volume before the hosts are quiesced. If the volume does not have sufficient free space available, the required amount of space must be added to the 7-Mode volume.

If transition fails during the import phase due to lack of space on the volume, the following EMS message is generated: LUN.vol.proc.fail.no.space: Processing for LUNs in volume vol_name failed due to lack of space.

If there are volumes containing space-reserved LUNs, growing the volume by 1MB per LUN might not provide sufficient space. In such cases, the amount of space that has to be added is the size of the Snapshot reserve for the volume. After space is added to the volume, you can use the lun transition start command to transition the LUNs.

*Related information*

xref:task_recovering_from_a_failed_lun_transition.adoc[Recovering from a failed LUN transition]

http://docs.netapp.com/ontap-9/index.jsp[NetApp Documentation: ONTAP 9]
