---
permalink: copy-free/task_configuring_zones_by_using_fc_zone_plan.html
sidebar: sidebar
keywords: 
summary: 'Before transitioning a SAN FC environment, you must configure zones by using the FC zone planner to group the initiator hosts and targets.'
---
= Configuring zones by using the FC zone plan
:icons: font
:imagesdir: ../media/

[.lead]
Before transitioning a SAN FC environment, you must configure zones by using the FC zone planner to group the initiator hosts and targets.

* The FC zone planner must be generated by using the Collect and Access feature of the 7-Mode Transition Tool
* The FC zone script file must be accessible.

. If there are any changes to the igroup configurations on the 7-Mode systems, modify and regenerate the FC zone plan.
+
xref:task_generating_an_assessment_report_by_adding_systems_to_7mtt.adoc[Generating an assessment report by adding systems to the 7-Mode Transition Tool]

. Log in to the CLI of the switch.
. Copy and execute the required zone commands one at a time.
+
The following example runs the zone commands on the switch:
+
----
switch1:admin>config terminal
# Enable NPIV feature
feature npiv
zone name auto_transition_igroup_d31_194bf3 vsan 10
member pwwn 21:00:00:c0:dd:19:4b:f3
member pwwn 20:07:00:a0:98:32:99:07
member pwwn 20:09:00:a0:98:32:99:07
.......
.......
.......
copy running-config startup-config
----

. Verify the data access from the cluster by using the test initiator hosts.
. After the verification is complete, perform the following steps:
 .. Disconnect the test initiator hosts.
 .. Remove the zone configuration.
