---
permalink: copy-free/task_generating_fc_zone_plan.html
sidebar: sidebar
keywords: ontap, transition, copy, free, fc, zone, plan
summary: 'For FC switches, you must generate an FC zone plan as part of the transition assessment report to configure the zones for grouping the initiator hosts and targets after the migration.'
---
= Generating an FC zone plan
:icons: font
:imagesdir: ../media/

[.lead]
For FC switches, you must generate an FC zone plan as part of the transition assessment report to configure the zones for grouping the initiator hosts and targets after the migration.

* The 7-Mode system, hosts, and the cluster must be connected to the same switch.
+
xref:concept_supported_configurations_for_generating_an_fc_zone_plan.adoc[Supported configurations for generating an FC zone plan]

* You must have created the required target SVMs and FC LIFs on the cluster.
* The FC LIFs that are created on the target SVMs will have WWPN, which are different from 7-Mode WWPNs. Therefore, perform FC zoning while you transition SAN for FCP.

.Steps
. In the Collect and Assess section, click *Add Systems*.
. In the Add System window, perform one of the following actions:
 ** Add a single system:
  ... Enter the FQDN or IP address of the system.
  ... Enter the user name and password for the specified system.
  ... Select the system type:
   **** Data ONTAP storage systems
   **** Hosts: Microsoft Windows, Red Hat Linux Enterprise, and VMware ESXi
   **** FC switches: Cisco and Brocade
 ** Add multiple systems by clicking *Browse*, and then selecting the text file that contains the credentials for multiple systems.
. Click *Add*.
+
If the assessment status of a system is Ready, then you can perform transition assessment for that system.

. Generate the transition assessment report with the FC zone plan:
 .. Select the systems, including the required FC switches, for transition assessment.
 .. Click *Create Transition Assessment Report*.
 .. In the pair systems and start FC zone planner dialog box, select the 7-Mode systems (single controller or HA pair), the switch connected to the cluster, and an SVM in the cluster.
+
If you plan to consolidate the FC LUNs to a single SVM by rehosting transitioned volumes, select the 7-Mode HA pair and the target SVM.
+
NOTE: It is a best practice to consolidate the FC LUNs to a single SVM for preserving the 7-Mode single-system image (SSI) configuration.
+
If you do not plan to consolidate the FC LUNs, you must generate the FC zone plan for each 7-Mode controller and the corresponding target SVM.

 .. Click *FC Zoning for paired systems*.
 .. In the Create Transition Assessment Report dialog box, select the Data ONTAP version of the target cluster.
 .. Specify a prefix for the file name of the reports.
 .. Click *Generate Report*.

The FC zone plan is generated as a `.zip` file. The plan contains zones created per the igroup configurations on the 7-Mode systems. Each zone contains a single initiator WWPN and multiple SVM target WWPNs.

You must use the FC zone plan for configuring the zones to group the initiator hosts and targets for providing data access from the cluster.
