---
permalink: copy-free/task_assessing_controllers_and_hosts.html
sidebar: sidebar
keywords: ontap, transition, copy, free, assess, controllers, hosts
summary: 'You can collect and assess information about the controllers and hosts by using either the 7-Mode Transition Tool or the Inventory Collect Tool, depending on the security regulations in your environment.'
---
= Assessing controllers and hosts
:icons: font
:imagesdir: ../media/

[.lead]
You can collect and assess information about the controllers and hosts by using either the 7-Mode Transition Tool or the Inventory Collect Tool, depending on the security regulations in your environment.

* The 7-Mode Transition Tool collects inventory information about controller and hosts by adding the systems or by using the inventory report generated by the Inventory Collect Tool.
+
The 7-Mode Transition Tool then assesses inventory information and creates the transition assessment report.

* You must be aware of the following considerations when performing transition assessment:
 ** You should not perform both assessment and migration operations simultaneously on a controller.
 ** You should avoid performing assessment operations on active storage controllers during peak hours.
