---
permalink: copy-free/task_rehosting_volumes_from_different_svms_to_a_single_svm.html
sidebar: sidebar
keywords: ontap, transition, copy, free, rehost, volumes, svm
summary: 'Volume rehost enables you to migrate a transitioned volume from one SVM to another SVM without data copy. The rehost operation enables you to consolidate all volumes that have FC LUNs to a single SVM, thereby preserving the 7-Mode single-system image \(SSI\) semantics. You can also rehost transitioned NAS volumes.'
---
= Rehosting transitioned volumes to a different SVM
:icons: font
:imagesdir: ../media/

[.lead]
Volume rehost enables you to migrate a transitioned volume from one SVM to another SVM without data copy. The rehost operation enables you to consolidate all volumes that have FC LUNs to a single SVM, thereby preserving the 7-Mode single-system image (SSI) semantics. You can also rehost transitioned NAS volumes.

* The volume that you want to rehost must be online.
* Volume management operations, such as volume move or LUN move, must not be running.
* Data access to the volume that is being rehosted must be stopped.
+
Rehosting is a disruptive operation.

The following volume policies, policy rules, and configurations are lost from the source volume and must be manually reconfigured on the rehosted volume after the rehost operation:

* Volume and qtree export policies
* Antivirus policies
* Volume efficiency policy
* Quality of Service (QoS) policies
* Snapshot policies
* Quota rules
* CIFS shares
* igroups associated with a portset

.Steps
* *Rehosting FC and iSCSI volumes*
 .. Switch to the advanced privilege level:
 +
`*set -privilege advanced*`
 .. Rehost the volume on the destination SVM:
+
[options="header"]
|===
| If you want to...| Run the following command...
a|
Unmap the LUNs after rehosting
a|
`*volume rehost -vserver _source_svm_ -volume _vol_name_ -destination-vserver _destination_svm_ -force–unmap-luns true*`
a|
Remap the LUNs to the same igroups after rehosting
a|
`*volume rehost -vserver _source_svm_ -volume _vol_name_ -destination-vserver _destination_svm_ -auto-remap-luns true*`
|===
* *Rehosting NFS volumes*
 .. Record information about the NFS export policies.
 .. Unmount the volume from the parent volume:
 +
`*volume unmount*`
 .. Switch to the advanced privilege level:
`*set -privilege advanced*`
 .. Rehost the volume on the destination SVM:
 +
`*volume rehost -vserver _source_svm_ -volume _vol_name_ -destination-vserver _destination_svm_*`
+
The default export policy of the destination SVM is applied to the rehosted volume.

 .. Create the export policy:
 +
`*vserver export-policy create*`
 .. Update the export policy of the rehosted volume to a user-defined export policy:
 +
`*volume modify*`
 .. Mount the volume under the appropriate junction path in the destination SVM:
 +
`*volume mount*`
 .. Verify that the NFS service is running on the destination SVM:
 +
`*vserver nfs status*`
 .. Resume NFS access to the rehosted volume.
+
Because the volume access path (LIFs and junction path) has undergone changes, you must update the NFS client credentials and LIF configurations to reflect the destination SVM LIFs.

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-nfs/home.html[NFS management]
* *Rehosting CIFS volumes*
 .. Record information about the CIFS shares.
 .. Unmount the volume from the parent volume:
 +
`*volume unmount*`
 .. Switch to the advanced privilege level:
 +
`*set -privilege advanced*`
 .. Rehost the volume on the destination SVM:
 +
`*volume rehost -vserver _source_svm_ -volume _vol_name_ -destination-vserver _destination_svm_*`
 .. Mount the volume under the appropriate junction path in the destination SVM:
 +
`*volume mount*`
 .. Create CIFS shares for the rehosted volume:
 +
`*vserver cifs share create*`
 .. If the DNS domains differ between the source and destination SVMs, create new users and groups.
 .. Update the CIFS client with the new destination SVM LIFs and junction path to the rehosted volume.

+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-cifs/home.html[SMB/CIFS management]
* *Rehosting volumes in SnapMirror relationships*
 .. Record the SnapMirror relationship type:
 +
`*snapmirror show*`
 .. From the destination cluster, delete the SnapMirror relationship:
 +
`*snapmirror delete*`
+
IMPORTANT: You must not break the SnapMirror relationship; otherwise, the data protection capability of the destination volume is lost and the relationship cannot be reestablished after the rehosting operation.

 .. From the source cluster, release the SnapMirror relationship information:
 +
`*snapmirror release*`
+
You set the -relationship-info-only parameter to true so that the Snapshot copies are not deleted and only the source relationship information is removed.

 .. Switch to the advanced privilege level:
 +
`*set -privilege advanced*`
 .. Rehost the volume on the destination SVM:
 +
`*volume rehost -vserver _source_svm_ -volume _vol_name_ -destination-vserver _destination_svm_*`
 .. Create the SVM peer relationship between the source and destination SVMs:
 +
`*vserver peer create*`
 .. Create the SnapMirror relationship between the source and destination volumes:
 +
`*snapmirror create*`
+
The rehosted volume can be the source or destination of the SnapMirror relationship.

 .. Resynchronize the data protection relationship:
 +
`*snapmirror resync*`

+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-dap/home.html[Data protection]

You must manually create the autovolume workloads for the rehosted volumes by performing the following steps:

. Create a user-defined policy group for the SVM:
+
`*qos policy-group create -vserver _destination-vserver_ -policy-group _policy-group-name_*`
. Assign the QoS policy group to the rehosted volume:
+
`*volume modify -vserver _destination-vserver_ -volume _rehosted-volume_ -qos-policy-_group policy-group-name_*`

You must manually reconfigure the policies and the associated rules on the rehosted volume.

NOTE: If the rehosting operation fails, you might need to reconfigure the volume policies and the associated rules on the source volume.

*Related information*

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html[ONTAP 9 commands]
