---
permalink: copy-free/task_transitioning_to_clustered_data_ontap_8_3_from_a_7_mode_version_with_32_bit_data.html
sidebar: sidebar
keywords: 
summary: '32-bit aggregates, volumes, and Snapshot copies are not supported in ONTAP 8.3 and later. Therefore, you must expand the 32-bit aggregates to 64-bit, and then find and remove any 32-bit volumes and Snapshot copies from the 7-Mode system before transition.'
---
= Preparing for transitioning 7-Mode systems with 32-bit aggregates
:icons: font
:imagesdir: ../media/

[.lead]
32-bit aggregates, volumes, and Snapshot copies are not supported in ONTAP 8.3 and later. Therefore, you must expand the 32-bit aggregates to 64-bit, and then find and remove any 32-bit volumes and Snapshot copies from the 7-Mode system before transition.

* *32-bit aggregates*
 .. xref:task_expanding_an_aggregate_to_the_64_bit_format_without_adding_storage.adoc[Expanding an aggregate to the 64-bit format]
 .. xref:task_finding_and_removing_32_bit_data_from_source_volumes_and_snapshot_copies.adoc[Finding and removing 32-bit volumes and Snapshot copies]
* *32-bit volumes or Snapshot copies*
+
Even if you have only 64-bit aggregates and volumes, some 32-bit or mixed-format FlexVol volumes or Snapshot copies might remain. You must remove these volumes and Snapshot copies before transition.
+
xref:task_finding_and_removing_32_bit_data_from_source_volumes_and_snapshot_copies.adoc[Finding and removing 32-bit volumes and Snapshot copies]

*Related information*

http://www.netapp.com/us/media/tr-3978.pdf[NetApp Technical Report 3978: In-Place Expansion of 32-Bit Aggregates to 64-Bit Overview and Best Practices]
