---
permalink: copy-free/task_generating_an_assessment_report_by_adding_systems_to_7mtt.html
sidebar: sidebar
keywords: 
summary: 'You can collect inventory information for controllers, hosts, and FC switches by adding the systems to the 7-Mode Transition Tool. You can then create an assessment report to assess the features and functionalities of those systems, and to identify how they work in the ONTAP version selected for transition.'
---
= Generating an assessment report by adding systems to the 7-Mode Transition Tool
:icons: font
:imagesdir: ../media/

[.lead]
You can collect inventory information for controllers, hosts, and FC switches by adding the systems to the 7-Mode Transition Tool. You can then create an assessment report to assess the features and functionalities of those systems, and to identify how they work in the ONTAP version selected for transition.

* The user name for the storage system and hosts must have sufficient privileges to execute the commands listed in the readme file.
+
The readme file is located at 7-Mode_Transition_Tool_installed_location\bin\ict.

* You must have prepared the 7-Mode systems, hosts, and FC switches for transition assessment.
* For assessing Windows systems, you must have a domain user account.
* If you are adding multiple systems for assessment, you must create a text file that is encoded in the ASCII or UTF-8 format and must contain the system details in the form of one system per line.
+
Each system details must be in the following format:
+
----
(ontap|windows|vmware|linux|cisco|brocade)://[(user|domain_user)[:password]@](host_name|ip)
----

* The controller or host must be accessible by the system on which the 7-Mode Transition Tool is installed and run.
* All features must be configured or their license enabled so that the workbook can contain inventory information about these features.
* The user name for the storage system must have sufficient administrative privileges to collect inventory information.
* All host names and storage system configurations, such as CIFS share names, user names, and group names, must be in the UTF-8 format.

If the 7-Mode Transition Tool service or the system on which this tool is installed is restarted, then the system details added to the tool are lost and the system must be added to the tool again.

. If you want to use the latest Interoperability Matrix (IMT) data for transition assessment:
 .. Download the IMT data from the Interoperability Matrix, and then save it:
  ... From the Reports menu, click *Complete Daily Exports*.
  ... In the Complete Daily Exports dialog box, enter FAS in the search field.
  ... Download the ONTAP SAN Host excel file, and then save it.
https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]
 .. From the CLI, import the IMT data by using the transition imt import command.
 .. Verify that the import is successful by using the transition imt show command.
+
*Troubleshooting:* If the IMT data import operation fails, you can revert to the previous data by using the transition imt restore command.
. Log in to the 7-Mode Transition Tool, and then click *Collect & Assess* in the home page.
. Click *Add Systems*.
. In the Add System window, perform one of the following actions:
 ** Add a single system:
  ... Enter the fully qualified domain name (FQDN) or IP address of the system.
  ... Enter the user name and password for the specified system.
  ... Select the system type:
   **** Data ONTAP storage systems
   **** Hosts: Microsoft Windows, Red Hat Linux Enterprise, and VMware ESXi
   **** FC switches: Cisco and Brocade
 ** Add multiple systems by clicking *Browse*, and then selecting the text file that contains the credentials for multiple systems.
. Click *Add*.
+
If the assessment status of a system is Ready, then you can perform transition assessment for that system.

. Generate the transition assessment report:
 .. Select the systems for transition assessment.
 .. Click *Create Transition Assessment Report*.
 .. In the Create Transition Assessment Report dialog box, select the Data ONTAP version of the target cluster.
 .. Specify a prefix for the file name of the reports.
 .. Click *Generate Report*.

+
The assessment workbook (report name appended with "`AssessmentWorkbook`") and assessment executive summary (report name appended with "`AssessmentExecutiveSummary`") reports are generated in XML format.
+
You can access the assessment workbook, assessment summary, and inventory XML files that are used to generate the assessment report from the ...etc/webapp/transition-gui/tmc folder.
. View the assessment workbook in Microsoft Excel and assessment executive summary in Microsoft Word by using Microsoft Office 2007 or later versions.
+
In the assessment workbook, see the Transition Feasibility (CFT), Config Precheck Summary, Config Precheck Details, and CFT Precheck Summary tabs for copy-free transition assessment details.
+
In the assessment executive summary, see the Copy-Free Transition Feasibility section for controller-level assessment details.
+
You might have to enable macros in Excel to view the assessment workbook.
+
In the data collection summary of the assessment workbook, if the access status of a system is FAILED, then the inventory information for that system is invalid. In the assessment executive summary, the value of some of the fields of this system is displayed as Not Assessed.
