---
permalink: copy-free/task_gathering_cabling_information_for_transition.html
sidebar: sidebar
keywords: ontap, transition, copy, free, gather, cabling, information
summary: 'Before starting copy-free transition, you must gather information about the adapters, ports, disk shelves, and storage connectivity of your 7-Mode controllers, and then plan how to connect the 7-Mode disk shelves to the target cluster nodes.'
---
= Gathering cabling information for transition
:icons: font
:imagesdir: ../media/

[.lead]
Before starting copy-free transition, you must gather information about the adapters, ports, disk shelves, and storage connectivity of your 7-Mode controllers, and then plan how to connect the 7-Mode disk shelves to the target cluster nodes.

You must have printed the copy-free transition cabling worksheet.

xref:reference_copy_free_transition_cabling_worksheet.adoc[Copy-free transition cabling worksheet]

. Use Config Advisor to perform a health check on the 7-Mode storage and cabling and collect cabling data.
+
You should use the `7-Mode Install Checks` option from the "`Data ONTAP 7 and 8 (7-Mode)`" execution profile.

. Gather the required information about each 7-Mode controller by using the following command:
+
`*sysconfig _slot_number_*`
+
You can use the output of this command to identify which ports are used for disk shelf connectivity.
+
----
host1> sysconfig 3
        slot 3: SAS Host Adapter 3a
                24 Disks:            13440.0GB
                1 shelf with IOM3
        slot 3: SAS Host Adapter 3b
                24 Disks:            13440.0GB
                1 shelf with IOM3
        slot 3: SAS Host Adapter 3c
                24 Disks:            13440.0GB
                1 shelf with IOM3
        slot 3: SAS Host Adapter 3d
                24 Disks:            13440.0GB
                1 shelf with IOM3
----

. From the cluster, run the following nodeshell command on each node:
+
`*system node run -node _node_name_ -command sysconfig -a*`
+
You can use the output of this command to obtain information about the available ports and expansion card slots.

. On the target cluster nodes, plan the ports to be used for connecting the 7-Mode disk shelves:
 .. Review the available (open) ports.
 .. Review the expansion card slots.
 .. Plan the expansion card configuration.
+
You can plan to move the expansion cards from the 7-Mode systems if they are also supported on the destination platform and ONTAP version. You can also plan for PAM cards, if required.
+
https://hwu.netapp.com[NetApp Hardware Universe]

 .. Plan the destination ports to use for the disk shelf cabling.
+
The selection of the destination ports depends on some of the following factors:

  *** Separate or existing disk shelf stack
  *** Port availability
  *** SAS or FC connections
  *** Availability of on-board ports or expansion cards
. Go to the data center to physically record the port connections on the 7-Mode controllers and target cluster nodes in the cabling worksheet:
 .. Record the used ports on the 7-Mode controllers in the cabling worksheet.
 .. Record the used ports on the target cluster nodes in the cabling worksheet.
 .. Record the destination ports to be used for connecting the 7-Mode disk shelves, as planned in Step <<STEP_D0CFE719A0384F7FA5D9E73C8EA6C2E7,#STEP_D0CFE719A0384F7FA5D9E73C8EA6C2E7>>.
 .. Ensure that you have the right cables for connecting the disk shelves.
+
You should identify any issues with cabling based on the new disk shelf stack location.

 .. Plan for longer cable lengths due to ladder racking or data center requirements.
 .. Label each disk shelf stack and cable on the 7-Mode controllers.
+
The best practice is to label the 7-Mode disk shelf stacks in case you want to roll back the transition and have to reconnect the disk shelves to the 7-Mode controllers.

*Related information*

[hw-unisas]

https://library.netapp.com/ecm/ecm_download_file/ECMP1119629[SAS Disk Shelves Installation and Service Guide for DS4243, DS2246, DS4486, and DS4246]

https://library.netapp.com/ecm/ecm_download_file/ECMM1280273[DiskShelf14mk2 AT Hardware Service Guide]

https://library.netapp.com/ecm/ecm_download_file/ECMP1112854[DS14mk2 FC, and DS14mk4 FC Hardware Service Guide]
