---
permalink: copy-free/task_running_manual_steps_for_rolling_back_the_transition.html
sidebar: sidebar
keywords: 
summary: 'You must perform some manual steps on the cluster and 7-Mode systems if you decide to roll back the transition. The list of manual rollback steps is generated by the 7-Mode Transition Tool.'
---
= Manually rolling back the transition
:icons: font
:imagesdir: ../media/

[.lead]
You must perform some manual steps on the cluster and 7-Mode systems if you decide to roll back the transition. The list of manual rollback steps is generated by the 7-Mode Transition Tool.

The rollback steps vary depending on the stage at which you decide to roll back. You must perform all steps in this task if you decide to roll back after a successful import operation. If you decide to roll back at an earlier stage, you have to perform a subset of these steps.

. Log in to the cluster.
. If any transitioned volume is in a SnapMirror relationship, choose one of the following actions:
 ** If a transitioned volume is the destination of a SnapMirror relationship, delete the SnapMirror relationship: `snapmirror delete -destination-path destination-path -source-path source-path`
 ** If a transitioned volume is the source of a SnapMirror relationship, release the SnapMirror relationship: `snapmirror release -destination-path destination-path -source-path source-path`
. From the cluster, verify that the following operations are not running on the transitioned volumes:
 .. Volume move operation: `volume move show`
 .. LUN move operation: `lun move show`
 .. LUN copy operation: `lun copy show`
. Perform the rollback for all of the 7-Mode aggregates:
 .. Log in to the diagnostic privilege level: `set -privilege diagnostic`
 .. Revert the aggregates to the 7-Mode state by using the storage transition revert start command.
+
This command requires additional parameters, such as the transition project ID and aggregate attributes. You should use the complete command with the parameters and its values, as generated by the 7-Mode Transition Tool.

 .. Verify that the rollback is successful for all of the transitioned aggregates: `storage transition revert show-status`
+
The status-code field for an aggregate is displayed as revert_complete when the rollback is successful.
. Reassign the disk ownerships from the target cluster nodes to the 7-Mode controllers:
 .. Assign disk ownership to the 7-Mode controllers: `disk assign –disk disk_id –s system_id -force true`
 .. Verify that the disk ownership is assigned to the 7-Mode controllers: `storage disk show -fields owner-id`
. Remove the 7-Mode LIFs from the SVMs: `network interface delete -vserver svm_name -lif lif_name`
. Remove the copy-free transition restrictions on the target cluster nodes from the diagnostic privilege level: `storage transition pre-commit end -session-id transition_project_id`
+
You can also perform this step after the rollback operation is completed and the 7-Mode controllers are operational.

. Delete the transition project information about the target cluster nodes by using the following diagnostic privilege level command: `storage transition purge-info -session-id transition_project_id`
+
You can also perform this step after the rollback operation is completed and the 7-Mode controllers are operational.

. If disk ownership autoassigment was disabled on the cluster nodes during the export and halt operation, enable it: `storage disk assign -auto true`
. Manually remove all of the configurations that the tool has transitioned to the target SVMs.
+
You can view the results of the SVM provision and import operations for information about the configurations transitioned by the tool.

. Remove the disk shelves from the target cluster nodes, and then reconnect them to the 7-Mode controllers.
+
TIP: You should use the Config Advisor tool to verify the cabling.

. If any 7-Mode disk shelf IDs were changed to resolve the conflicts with the disk shelf IDs of the target cluster nodes, manually change them to the old IDs and power-cycle the disk shelves for the new IDs to take effect.
. Boot the source 7-Mode controllers in to the normal mode.
. From one of the source 7-Mode controllers, enable the takeover capability: `cf enable`
. If automatic deletion of aggregate Snapshot copies was disabled during the export and halt operation, enable it: `options snap autodelete aggr_name on`
