---
permalink: copy-free/task_generating_an_assessment_report_by_importing_inventory_report_xml.html
sidebar: sidebar
keywords: ontap, transition, copy, free, inventory, report, xml, assessment, import
summary: 'You can import the inventory XML report generated by the Inventory Collect Tool to assess the features and functionalities of hosts and controllers. You can then identify how these host and controllers work in the ONTAP version selected for transition by creating an assessment report.'
---
= Generating an assessment report by importing the inventory report XML
:icons: font
:imagesdir: ../media/

[.lead]
You can import the inventory XML report generated by the Inventory Collect Tool to assess the features and functionalities of hosts and controllers. You can then identify how these host and controllers work in the ONTAP version selected for transition by creating an assessment report.

* You must have run the Inventory Collect Tool and generated the inventory report XML file.
+
NOTE: To assess hosts and controllers for copy-free transition, you must use Inventory Collect Tool 3.3 to collect inventory.

* You must have prepared the 7-Mode systems and hosts for transition assessment.

The systems that you want to assess need not be reachable while importing the inventory report and performing transition assessment.

.Steps
. Log in to the 7-Mode Transition Tool, and then click *Collect and Assess* in the home page.
. Click *Import Inventory Report XML*.
. Click *Browse*, and then select the XML report generated by the Inventory Collect Tool.
. Click *Import*.
+
The assessment status of the system shows `Imported;Ready`.

. Select the system for which you want to perform transition assessment.
. Click *Create Transition Assessment Report*.
. In the Create Transition Assessment Report dialog box, select the Data ONTAP version of the target cluster.
. Specify a prefix for the file name of the reports.
. Click *Generate Report*.
+
The AssessmentWorkbook and AssessmentExecutiveSummary reports are generated in XML format.

. View the AssessmentWorkbook report in Microsoft Excel and the AssessmentExecutiveSummary report in Microsoft Word by using Microsoft Office 2007 or later versions.
+
To view the AssessmentWorkbook report in Microsoft Excel, you might have to enable macros in Excel.
