---
permalink: snapmirror/task_recovering_from_a_disaster_at_7_mode_during_transition.html
sidebar: sidebar
keywords: 
summary: 'If you have established a SnapMirror disaster recovery \(DR\) relationship between the 7-Mode primary volume and the clustered Data ONTAP secondary volume and if a disaster occurs at the 7-Mode primary site, you can direct client access to the clustered Data ONTAP secondary volume. After the 7-Mode primary volume is brought back online, you have to perform additional steps to redirect the clients to the clustered Data ONTAP primary volume.'
---
= Recovering from a disaster at the 7-Mode site during transition
:icons: font
:imagesdir: ../media/

[.lead]
If you have established a SnapMirror disaster recovery (DR) relationship between the 7-Mode primary volume and the clustered Data ONTAP secondary volume and if a disaster occurs at the 7-Mode primary site, you can direct client access to the clustered Data ONTAP secondary volume. After the 7-Mode primary volume is brought back online, you have to perform additional steps to redirect the clients to the clustered Data ONTAP primary volume.

To retain any data written on the clustered Data ONTAP secondary volume after the disaster, you must transition the 7-Mode primary volume after the 7-Mode primary volume is back online and establish a SnapMirror relationship between the clustered Data ONTAP primary and secondary volumes. You can then redirect the clients to the clustered Data ONTAP primary volumes.

SnapMirror resynchronization from clustered Data ONTAP volumes to the 7-Mode volumes is not supported. Therefore, if you reestablish the DR relationship between the 7-Mode primary volume and the clustered Data ONTAP secondary volume after the disaster, any data written on the secondary clustered Data ONTAP will be lost.
